2018-09-14 03:19:27.414 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:19:27.417 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:20:27.414 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:20:27.417 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:21:27.414 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:21:27.417 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:21:35.981 19943 DEBUG oslo_concurrency.lockutils [req-f78bc632-6447-4925-b930-fd6de23b3441 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:21:36.827 19943 DEBUG neutron.agent.dhcp.agent [req-9fa245d5-7ab1-4d25-8401-a718f7276934 - - - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:21:36.829 19943 DEBUG neutron.agent.linux.utils [req-9fa245d5-7ab1-4d25-8401-a718f7276934 - - - - -] Unable to access /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:36.830 19943 DEBUG neutron.agent.linux.dhcp [req-9fa245d5-7ab1-4d25-8401-a718f7276934 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-639ca2f0-e100-40d8-9456-d5b471358e13 on network 639ca2f0-e100-40d8-9456-d5b471358e13 does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1272
2018-09-14 03:21:36.831 19943 DEBUG neutron.agent.linux.dhcp [req-9fa245d5-7ab1-4d25-8401-a718f7276934 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-639ca2f0-e100-40d8-9456-d5b471358e13 on network 639ca2f0-e100-40d8-9456-d5b471358e13 does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1293
2018-09-14 03:21:39.860 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.879 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.894 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.917 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.935 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.952 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', 'link', 'set', 'tapdf877620-3e', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.981 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-o', 'link', 'show', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:39.998 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-14 03:21:40.245 19943 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tapdf877620-3e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-14 03:21:40.247 19943 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-09-14 03:21:40.248 19943 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tapdf877620-3e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-14 03:21:40.249 19943 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Port, col_values=(('tag', 4095),), record=tapdf877620-3e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-14 03:21:40.251 19943 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=2): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'df877620-3eb4-400d-a64e-4083aa851ff7', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:91:a5:74'})), record=tapdf877620-3e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-14 03:21:40.276 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapdf877620-3e', 'address', 'fa:16:3e:91:a5:74'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.292 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.302 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapdf877620-3e', 'netns', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.320 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', 'link', 'set', 'tapdf877620-3e', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.337 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', 'link', 'set', 'tapdf877620-3e', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.352 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Acquired semaphore "iptables-qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:21:40.354 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.375 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.395 19943 DEBUG neutron.agent.linux.iptables_manager [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-09-14 03:21:40.396 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Releasing semaphore "iptables-qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:21:40.397 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-o', 'link', 'show', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.409 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', 'addr', 'show', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.424 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'addr', 'add', '11.153.1.2/24', 'scope', 'global', 'dev', 'tapdf877620-3e', 'brd', '11.153.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.439 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.451 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Setting IPv4 gateway for dhcp netns on net 639ca2f0-e100-40d8-9456-d5b471358e13 to 11.153.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1169
2018-09-14 03:21:40.453 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.153.1.1', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.467 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.481 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Cleaning stale devices for network 639ca2f0-e100-40d8-9456-d5b471358e13 _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1374
2018-09-14 03:21:40.482 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.492 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.511 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Building initial lease file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:626
2018-09-14 03:21:40.513 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Done building initial lease file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/leases with contents:
1536996100 fa:16:3e:91:a5:74 11.153.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:654
2018-09-14 03:21:40.513 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:21:40.515 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:21:40.517 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Unable to access /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:40.519 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host', '--addn-hosts=/var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tapdf877620-3e', '--dhcp-range=set:tag0,11.153.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:40.551 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:40.552 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:40.552 19943 DEBUG neutron.agent.linux.external_process [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:21:40.554 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:21:40.555 19943 DEBUG oslo_concurrency.lockutils [req-f78bc632-6447-4925-b930-fd6de23b3441 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:21:41.104 19943 DEBUG neutron.agent.dhcp.agent [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:21:41.106 19943 DEBUG neutron.agent.linux.dhcp [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:21:41.115 19943 DEBUG neutron.agent.linux.dhcp [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:21:41.122 19943 DEBUG neutron.agent.linux.utils [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:41.141 19943 DEBUG neutron.agent.linux.dhcp [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:21:41.142 19943 DEBUG neutron.agent.linux.utils [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:41.155 19943 DEBUG neutron.agent.linux.utils [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:41.167 19943 DEBUG neutron.agent.linux.utils [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:41.169 19943 DEBUG neutron.agent.linux.utils [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:41.170 19943 DEBUG neutron.agent.linux.external_process [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:21:41.171 19943 DEBUG oslo_concurrency.lockutils [req-baf412b0-1464-447a-a9c6-35013ceeb22f - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:21:41.172 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:21:41.173 19943 DEBUG neutron.agent.dhcp.agent [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-14T07:21:37Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-639ca2f0-e100-40d8-9456-d5b471358e13, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.2'}], id=df877620-3eb4-400d-a64e-4083aa851ff7, mac_address=fa:16:3e:91:a5:74, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=False, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:21:37Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:410
2018-09-14 03:21:41.174 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:21:41.176 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:21:41.177 19943 INFO neutron.agent.dhcp.agent [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-14T07:21:37Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-639ca2f0-e100-40d8-9456-d5b471358e13, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.2'}], id=df877620-3eb4-400d-a64e-4083aa851ff7, mac_address=fa:16:3e:91:a5:74, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=False, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:21:39Z
2018-09-14 03:21:41.207 19943 DEBUG neutron.agent.dhcp.agent [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:21:41.210 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:21:41.212 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:21:41.220 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:41.233 19943 DEBUG neutron.agent.linux.dhcp [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:21:41.234 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:41.247 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:21:41.264 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:41.265 19943 DEBUG neutron.agent.linux.utils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:21:41.266 19943 DEBUG neutron.agent.linux.external_process [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:21:41.267 19943 DEBUG oslo_concurrency.lockutils [req-34903ff7-e97e-4550-ba05-8e698810e5ab - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:13.780 19943 DEBUG oslo_concurrency.lockutils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:13.781 19943 INFO neutron.agent.dhcp.agent [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-14T07:22:12Z, description=, device_id=5894afdd-0e6f-498f-93d3-88045532ff0a, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.1'}], id=c2e39e2b-8609-40b8-8651-2e51e7a3447f, mac_address=fa:16:3e:a0:2e:f0, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=False, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:12Z
2018-09-14 03:22:13.784 19943 DEBUG neutron.agent.dhcp.agent [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:13.788 19943 DEBUG neutron.agent.linux.dhcp [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:13.791 19943 DEBUG neutron.agent.linux.dhcp [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:13.797 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:13.816 19943 DEBUG neutron.agent.linux.dhcp [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:13.818 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:13.836 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:13.853 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:13.854 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:13.854 19943 DEBUG neutron.agent.linux.external_process [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:13.855 19943 DEBUG oslo_concurrency.lockutils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:15.006 19943 DEBUG oslo_concurrency.lockutils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:15.007 19943 INFO neutron.agent.dhcp.agent [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-14T07:22:12Z, description=, device_id=5894afdd-0e6f-498f-93d3-88045532ff0a, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.1'}], id=c2e39e2b-8609-40b8-8651-2e51e7a3447f, mac_address=fa:16:3e:a0:2e:f0, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=False, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:12Z
2018-09-14 03:22:15.009 19943 DEBUG neutron.agent.dhcp.agent [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:15.011 19943 DEBUG neutron.agent.linux.dhcp [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:15.014 19943 DEBUG neutron.agent.linux.dhcp [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:15.020 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:15.036 19943 DEBUG neutron.agent.linux.dhcp [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:15.042 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:15.059 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:15.078 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:15.079 19943 DEBUG neutron.agent.linux.utils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:15.080 19943 DEBUG neutron.agent.linux.external_process [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:15.081 19943 DEBUG oslo_concurrency.lockutils [req-25d69216-0ff4-4fbf-8851-5b9dc7f974cf 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:17.429 19943 DEBUG oslo_concurrency.lockutils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:17.431 19943 INFO neutron.agent.dhcp.agent [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-14T07:22:12Z, description=, device_id=5894afdd-0e6f-498f-93d3-88045532ff0a, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.1'}], id=c2e39e2b-8609-40b8-8651-2e51e7a3447f, mac_address=fa:16:3e:a0:2e:f0, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=False, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:14Z
2018-09-14 03:22:17.433 19943 DEBUG neutron.agent.dhcp.agent [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:17.435 19943 DEBUG neutron.agent.linux.dhcp [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:17.438 19943 DEBUG neutron.agent.linux.dhcp [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:17.445 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:17.463 19943 DEBUG neutron.agent.linux.dhcp [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:17.464 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:17.479 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:17.492 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:17.494 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:17.494 19943 DEBUG neutron.agent.linux.external_process [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:17.496 19943 DEBUG oslo_concurrency.lockutils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:18.768 19943 DEBUG oslo_concurrency.lockutils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:18.769 19943 INFO neutron.agent.dhcp.agent [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-14T07:22:12Z, description=, device_id=5894afdd-0e6f-498f-93d3-88045532ff0a, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.1'}], id=c2e39e2b-8609-40b8-8651-2e51e7a3447f, mac_address=fa:16:3e:a0:2e:f0, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=False, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=6, security_groups=[], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:18Z
2018-09-14 03:22:18.771 19943 DEBUG neutron.agent.dhcp.agent [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:18.773 19943 DEBUG neutron.agent.linux.dhcp [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:18.776 19943 DEBUG neutron.agent.linux.dhcp [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:18.781 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:18.804 19943 DEBUG neutron.agent.linux.dhcp [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:18.806 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:18.825 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:18.839 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:18.840 19943 DEBUG neutron.agent.linux.utils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:18.841 19943 DEBUG neutron.agent.linux.external_process [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:18.842 19943 DEBUG oslo_concurrency.lockutils [req-fa5df1cb-e42d-48e1-9112-50304406eefe - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:27.369 19943 DEBUG oslo_concurrency.lockutils [req-3f752138-dd39-4c91-b22a-3c85e8047461 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Acquired semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:27.369 19943 DEBUG oslo_concurrency.lockutils [req-3f752138-dd39-4c91-b22a-3c85e8047461 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Releasing semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:27.415 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:22:27.417 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:22:30.783 19943 DEBUG oslo_concurrency.lockutils [req-a3ad5d6b-6d33-46cd-89a6-d28818fba155 - - - - -] Acquired semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:30.784 19943 DEBUG oslo_concurrency.lockutils [req-a3ad5d6b-6d33-46cd-89a6-d28818fba155 - - - - -] Releasing semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:31.724 19943 DEBUG oslo_concurrency.lockutils [req-a3ad5d6b-6d33-46cd-89a6-d28818fba155 - - - - -] Acquired semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:31.725 19943 DEBUG oslo_concurrency.lockutils [req-a3ad5d6b-6d33-46cd-89a6-d28818fba155 - - - - -] Releasing semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:52.089 19943 DEBUG oslo_concurrency.lockutils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:52.090 19943 INFO neutron.agent.dhcp.agent [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-14T07:22:50Z, description=, device_id=265b2854-ded9-4039-a9ec-ad25b81359f5, device_owner=, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.4'}], id=1c4698f5-63fe-434f-b21b-fe5a2571e9e4, mac_address=fa:16:3e:df:b6:58, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=True, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=3, security_groups=[u'4b7e2283-8049-4287-8f2d-1e16a8c97854'], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:51Z
2018-09-14 03:22:52.091 19943 DEBUG neutron.agent.dhcp.agent [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:52.094 19943 DEBUG neutron.agent.linux.dhcp [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:52.097 19943 DEBUG neutron.agent.linux.dhcp [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:52.105 19943 DEBUG neutron.agent.linux.utils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:52.122 19943 DEBUG neutron.agent.linux.dhcp [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:52.123 19943 DEBUG neutron.agent.linux.utils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:52.140 19943 DEBUG neutron.agent.linux.utils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:52.155 19943 DEBUG neutron.agent.linux.utils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:52.156 19943 DEBUG neutron.agent.linux.utils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:52.157 19943 DEBUG neutron.agent.linux.external_process [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:52.158 19943 DEBUG oslo_concurrency.lockutils [req-94086230-0553-401b-a645-103945b4e02a 2d5b02ec82284005bb29c0502d218330 ed2f585629c6407295b0d2227c8d8bad - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:54.905 19943 DEBUG oslo_concurrency.lockutils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:54.905 19943 INFO neutron.agent.dhcp.agent [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-14T07:22:50Z, description=, device_id=265b2854-ded9-4039-a9ec-ad25b81359f5, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.4'}], id=1c4698f5-63fe-434f-b21b-fe5a2571e9e4, mac_address=fa:16:3e:df:b6:58, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=True, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=4, security_groups=[u'4b7e2283-8049-4287-8f2d-1e16a8c97854'], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:54Z
2018-09-14 03:22:54.907 19943 DEBUG neutron.agent.dhcp.agent [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:54.908 19943 DEBUG neutron.agent.linux.dhcp [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:54.910 19943 DEBUG neutron.agent.linux.dhcp [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:54.915 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:54.935 19943 DEBUG neutron.agent.linux.dhcp [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:54.936 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:54.948 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:54.960 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:54.961 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:54.962 19943 DEBUG neutron.agent.linux.external_process [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:54.963 19943 DEBUG oslo_concurrency.lockutils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:22:55.880 19943 DEBUG oslo_concurrency.lockutils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:22:55.882 19943 INFO neutron.agent.dhcp.agent [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-14T07:22:50Z, description=, device_id=265b2854-ded9-4039-a9ec-ad25b81359f5, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'9a533e28-7d3b-48b8-8b5c-93f92eb08315', u'ip_address': u'11.153.1.4'}], id=1c4698f5-63fe-434f-b21b-fe5a2571e9e4, mac_address=fa:16:3e:df:b6:58, name=, network_id=639ca2f0-e100-40d8-9456-d5b471358e13, port_security_enabled=True, project_id=ed2f585629c6407295b0d2227c8d8bad, revision_number=5, security_groups=[u'4b7e2283-8049-4287-8f2d-1e16a8c97854'], status=DOWN, tags=[], tenant_id=ed2f585629c6407295b0d2227c8d8bad, updated_at=2018-09-14T07:22:55Z
2018-09-14 03:22:55.883 19943 DEBUG neutron.agent.dhcp.agent [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:22:55.884 19943 DEBUG neutron.agent.linux.dhcp [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:22:55.887 19943 DEBUG neutron.agent.linux.dhcp [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:22:55.891 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:55.904 19943 DEBUG neutron.agent.linux.dhcp [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:22:55.906 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:55.917 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:22:55.931 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:55.932 19943 DEBUG neutron.agent.linux.utils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:22:55.933 19943 DEBUG neutron.agent.linux.external_process [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:22:55.934 19943 DEBUG oslo_concurrency.lockutils [req-1ec08ae4-bf97-484e-b0b0-232b380c9873 10c05a22cea847f7a42d788fe8f1cd2e 368f193974e14846a186e2cbdb34d110 - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:23:27.416 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:23:27.419 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:23:32.689 19943 DEBUG oslo_concurrency.lockutils [req-78477173-9f0e-4bd2-9fa5-012a6834ed65 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:23:32.690 19943 DEBUG oslo_concurrency.lockutils [req-78477173-9f0e-4bd2-9fa5-012a6834ed65 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Releasing semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:23:34.396 19943 DEBUG oslo_concurrency.lockutils [req-78477173-9f0e-4bd2-9fa5-012a6834ed65 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:23:34.397 19943 DEBUG oslo_concurrency.lockutils [req-78477173-9f0e-4bd2-9fa5-012a6834ed65 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Releasing semaphore "dhcp-agent-network-lock-990b4ddf-dd04-44e0-920c-02fce451b987" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:24:27.416 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:24:27.421 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:25:27.416 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:25:27.420 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:26:27.416 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:26:27.420 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:27:18.091 19943 DEBUG oslo_concurrency.lockutils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:27:18.092 19943 DEBUG neutron.agent.dhcp.agent [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:27:18.094 19943 DEBUG neutron.agent.linux.utils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'dhcp_release', 'tapdf877620-3e', '11.153.1.4', 'fa:16:3e:df:b6:58'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:27:18.116 19943 DEBUG neutron.agent.linux.dhcp [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:27:18.129 19943 DEBUG neutron.agent.linux.dhcp [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:27:18.139 19943 DEBUG neutron.agent.linux.utils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:27:18.153 19943 DEBUG neutron.agent.linux.dhcp [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:27:18.154 19943 DEBUG neutron.agent.linux.utils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:27:18.166 19943 DEBUG neutron.agent.linux.utils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:27:18.179 19943 DEBUG neutron.agent.linux.utils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:27:18.181 19943 DEBUG neutron.agent.linux.utils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:27:18.181 19943 DEBUG neutron.agent.linux.external_process [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:27:18.182 19943 DEBUG oslo_concurrency.lockutils [req-b541f7f0-36c8-4a84-94be-5e81490342e9 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:27:27.416 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:27:27.419 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:28:06.547 19943 DEBUG oslo_concurrency.lockutils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:28:06.548 19943 DEBUG neutron.agent.dhcp.agent [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:28:06.550 19943 DEBUG neutron.agent.linux.utils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'dhcp_release', 'tapdf877620-3e', '11.153.1.1', 'fa:16:3e:a0:2e:f0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:06.569 19943 DEBUG neutron.agent.linux.dhcp [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Building host file: /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-14 03:28:06.577 19943 DEBUG neutron.agent.linux.dhcp [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Done building host file /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-14 03:28:06.585 19943 DEBUG neutron.agent.linux.utils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:06.594 19943 DEBUG neutron.agent.linux.dhcp [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Reloading allocations for network: 639ca2f0-e100-40d8-9456-d5b471358e13 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-14 03:28:06.595 19943 DEBUG neutron.agent.linux.utils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-4', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:06.606 19943 DEBUG neutron.agent.linux.utils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13', 'ip', '-6', 'route', 'list', 'dev', 'tapdf877620-3e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:06.618 19943 DEBUG neutron.agent.linux.utils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:28:06.619 19943 DEBUG neutron.agent.linux.utils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:28:06.620 19943 DEBUG neutron.agent.linux.external_process [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:28:06.621 19943 DEBUG oslo_concurrency.lockutils [req-a73adf0e-e4a7-4f4a-9325-2ad9bb8754c1 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:28:27.417 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:28:27.420 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 03:28:34.855 19943 DEBUG oslo_concurrency.lockutils [req-27dc1c86-f768-4335-a7c0-dbd9e9ad971f d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:28:34.857 19943 DEBUG neutron.agent.dhcp.agent [req-27dc1c86-f768-4335-a7c0-dbd9e9ad971f d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:28:34.860 19943 DEBUG neutron.agent.linux.utils [req-27dc1c86-f768-4335-a7c0-dbd9e9ad971f d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command (rootwrap daemon): ['kill', '-9', '23979'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:34.881 19943 DEBUG neutron.agent.linux.utils [req-27dc1c86-f768-4335-a7c0-dbd9e9ad971f d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-14 03:28:34.916 19943 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=br-int, port=tapdf877620-3e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-14 03:28:35.004 19943 DEBUG neutron.agent.linux.utils [req-52e8717b-e3b9-4017-ac43-aeec611160ba - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:35.015 19943 DEBUG neutron.agent.linux.utils [req-52e8717b-e3b9-4017-ac43-aeec611160ba - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'delete', 'qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:35.027 19943 DEBUG oslo_concurrency.lockutils [req-52e8717b-e3b9-4017-ac43-aeec611160ba - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:28:43.693 19943 DEBUG oslo_concurrency.lockutils [req-92a4cc22-2d35-4d3e-b728-50386466633e d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:28:43.981 19943 DEBUG neutron.agent.linux.utils [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:28:43.982 19943 DEBUG neutron.agent.linux.utils [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] Unable to access /var/lib/neutron/external/pids/639ca2f0-e100-40d8-9456-d5b471358e13.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:28:43.983 19943 DEBUG neutron.agent.linux.external_process [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:28:43.984 19943 DEBUG neutron.agent.dhcp.agent [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] Calling driver for network: 639ca2f0-e100-40d8-9456-d5b471358e13 action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-14 03:28:43.985 19943 DEBUG neutron.agent.linux.utils [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] Unable to access /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:28:43.986 19943 DEBUG neutron.agent.linux.utils [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] Unable to access /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-14 03:28:43.987 19943 DEBUG neutron.agent.linux.external_process [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] No process started for 639ca2f0-e100-40d8-9456-d5b471358e13 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-14 03:28:43.988 19943 DEBUG neutron.agent.linux.dhcp [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] Unable to access /var/lib/neutron/dhcp/639ca2f0-e100-40d8-9456-d5b471358e13/interface _get_value_from_conf_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:271
2018-09-14 03:28:43.988 19943 DEBUG neutron.agent.linux.dhcp [req-d5944879-def6-46d0-8bcb-d2420d6e0d2d - - - - -] No interface exists for network 639ca2f0-e100-40d8-9456-d5b471358e13 destroy /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1487
2018-09-14 03:28:44.028 19943 DEBUG neutron.agent.linux.utils [req-7681037f-f022-4583-8a7d-4988914490ae - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-14 03:28:44.043 19943 DEBUG neutron.agent.linux.dhcp [req-7681037f-f022-4583-8a7d-4988914490ae - - - - -] Namespace already deleted: qdhcp-639ca2f0-e100-40d8-9456-d5b471358e13 _destroy_namespace_and_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:249
2018-09-14 03:28:44.044 19943 DEBUG oslo_concurrency.lockutils [req-7681037f-f022-4583-8a7d-4988914490ae - - - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:28:45.454 19943 DEBUG oslo_concurrency.lockutils [req-92a4cc22-2d35-4d3e-b728-50386466633e d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Acquired semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-14 03:28:45.455 19943 DEBUG oslo_concurrency.lockutils [req-92a4cc22-2d35-4d3e-b728-50386466633e d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - - -] Releasing semaphore "dhcp-agent-network-lock-639ca2f0-e100-40d8-9456-d5b471358e13" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-14 03:29:04.795 19943 DEBUG neutron.agent.dhcp.agent [req-4e4858e5-31a2-4bea-aabd-3ec4b1075f56 - - - - -] resync (639ca2f0-e100-40d8-9456-d5b471358e13): ['Agent port was deleted'] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:256
2018-09-14 03:29:04.797 19943 INFO neutron.agent.dhcp.agent [req-4e4858e5-31a2-4bea-aabd-3ec4b1075f56 - - - - -] Synchronizing state
2018-09-14 03:29:05.603 19943 INFO neutron.agent.dhcp.agent [req-5305d1f8-ca01-49cc-8154-24abb8f1feca - - - - -] All active networks have been fetched through RPC.
2018-09-14 03:29:05.604 19943 INFO neutron.agent.dhcp.agent [-] Starting network 990b4ddf-dd04-44e0-920c-02fce451b987 dhcp configuration
2018-09-14 03:29:05.605 19943 INFO neutron.agent.dhcp.agent [-] Finished network 990b4ddf-dd04-44e0-920c-02fce451b987 dhcp configuration
2018-09-14 03:29:05.606 19943 INFO neutron.agent.dhcp.agent [req-5305d1f8-ca01-49cc-8154-24abb8f1feca - - - - -] Synchronizing state complete
2018-09-14 03:29:27.417 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 03:29:27.420 19943 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
