2018-09-28 15:00:57.094 20837 DEBUG nova.api.openstack.wsgi [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:00:57.099 20837 DEBUG nova.compute.api [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 28, 18, 46, 14, 192287, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:00:57.117 20837 DEBUG oslo_concurrency.lockutils [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:00:57.118 20837 DEBUG oslo_concurrency.lockutils [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:00:57.193 20837 DEBUG nova.compute.api [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:00:57.194 20837 DEBUG nova.compute.api [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:00:57.195 20837 DEBUG oslo_concurrency.lockutils [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:00:57.196 20837 DEBUG oslo_concurrency.lockutils [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:00:57.292 20837 DEBUG nova.policy [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'd620094bd6d047979241572f64ecaca7', 'roles': [u'admin', u'ResellerAdmin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'368f193974e14846a186e2cbdb34d110', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:00:57.296 20837 INFO nova.osapi_compute.wsgi.server [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] 10.0.20.23 "GET /v2.1/368f193974e14846a186e2cbdb34d110/servers/detail?all_tenants=True&changes-since=2018-09-28T18%3A46%3A14.192287%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.6115539
2018-09-28 15:01:40.862 20840 DEBUG nova.osapi_compute.wsgi.server [req-ad06b95a-ac17-4280-964f-68d83708ee98 d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - default default] (20840) accepted ('10.0.20.23', 50180) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:01:41.327 20840 DEBUG nova.api.openstack.wsgi [req-a43a27a1-b2dc-44fb-8e81-270d21263c89 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Action: 'create', calling method: <function version_select at 0x7f1e2c45a230>, body: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAX8ivecNjTIANEFqke7hBW+KZm8e4b5vjd2CqBWwrXk4EGO31r+umiyZBcQ8Xkeg+0M+NkGod9wAo8OkQdd+q+QUkCmXp365IWr/tdIAzCJanqZgga3mumGiTesbb6bZ/o1I70qW88FuWjIhWleShz3mGRDIifFMLXnUiXxnlMyXIlcfgN05buGgbVD1kLsak+hBF9iYVkRP5g0LVCSWqN5TH2741LTBNbWtKzk0bRdbJgpO9g2EECyFX98F5geYmCij18tHuRXwJ7vNKVnja8SinirlRThRv4HpVpxvMUlxJjBHko5QD5/ZsuY3QpIwXa+5YqatSb1/EHxgZol4l root@localhost.localdomain\n", "name": "tempest-keypair-1538161238"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:01:41.461 20840 DEBUG nova.quota [req-a43a27a1-b2dc-44fb-8e81-270d21263c89 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Getting quotas for project 8bef18ab502f4677940a913a5a7256ec. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 15:01:41.472 20840 DEBUG nova.quota [req-a43a27a1-b2dc-44fb-8e81-270d21263c89 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Getting quotas for user 8346f77a389b4e73990ce091147f8a00 and project 8bef18ab502f4677940a913a5a7256ec. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 15:01:41.589 20840 INFO nova.osapi_compute.wsgi.server [req-a43a27a1-b2dc-44fb-8e81-270d21263c89 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "POST /v2.1/8bef18ab502f4677940a913a5a7256ec/os-keypairs HTTP/1.1" status: 200 len: 997 time: 0.7235510
2018-09-28 15:01:47.884 20837 DEBUG nova.osapi_compute.wsgi.server [req-f4d6ea66-599e-4ae4-a2e9-805b61c0eb74 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] (20837) accepted ('10.0.20.23', 50226) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:01:48.313 20837 DEBUG nova.api.openstack.wsgi [req-cd3f7d64-4ad1-41ac-8573-c8da8d17f519 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<function version_select at 0x7f1e2c3decf8>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:01:48.319 20837 WARNING oslo_db.sqlalchemy.utils [req-cd3f7d64-4ad1-41ac-8573-c8da8d17f519 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-28 15:01:48.334 20837 WARNING oslo_db.sqlalchemy.utils [req-cd3f7d64-4ad1-41ac-8573-c8da8d17f519 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-28 15:01:48.344 20837 INFO nova.osapi_compute.wsgi.server [req-cd3f7d64-4ad1-41ac-8573-c8da8d17f519 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/os-keypairs HTTP/1.1" status: 200 len: 966 time: 0.4576809
2018-09-28 15:03:47.252 20837 DEBUG nova.osapi_compute.wsgi.server [req-cd3f7d64-4ad1-41ac-8573-c8da8d17f519 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20837) accepted ('10.0.20.23', 52678) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:03:47.676 20837 DEBUG nova.api.openstack.wsgi [req-631d6887-f637-45ba-b0e0-d281f8c34549 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f1e2cfd9090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:03:47.749 20837 INFO nova.api.openstack.wsgi [req-631d6887-f637-45ba-b0e0-d281f8c34549 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] HTTP exception thrown: Flavor m1.tiny could not be found.
2018-09-28 15:03:47.750 20837 DEBUG nova.api.openstack.wsgi [req-631d6887-f637-45ba-b0e0-d281f8c34549 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Returning 404 to user: Flavor m1.tiny could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-28 15:03:47.752 20837 INFO nova.osapi_compute.wsgi.server [req-631d6887-f637-45ba-b0e0-d281f8c34549 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/flavors/m1.tiny HTTP/1.1" status: 404 len: 500 time: 0.4966719
2018-09-28 15:03:47.774 20837 DEBUG nova.api.openstack.wsgi [req-78654a0b-e99e-44ca-8d3f-55e0c4f2684f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f1e2d04e850>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:03:47.829 20837 INFO nova.osapi_compute.wsgi.server [req-78654a0b-e99e-44ca-8d3f-55e0c4f2684f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/flavors HTTP/1.1" status: 200 len: 2106 time: 0.0617940
2018-09-28 15:03:47.849 20837 DEBUG nova.api.openstack.wsgi [req-7282fea7-4098-47d0-891d-74a66372305e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f1e2cfd9090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:03:47.873 20837 INFO nova.osapi_compute.wsgi.server [req-7282fea7-4098-47d0-891d-74a66372305e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0288539
2018-09-28 15:03:48.837 20837 DEBUG nova.api.openstack.wsgi [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Action: 'create', calling method: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc64450>>, body: {"server": {"name": "tempest-INSTANCE_SAMPLE-1538161238", "imageRef": "12a419bc-ac53-4807-ab39-866cafa926c2", "key_name": "tempest-keypair-1538161238", "flavorRef": "1", "max_count": 1, "min_count": 1, "networks": [{"uuid": "ad8e4dfd-1ea8-440d-809d-b153de92fe01"}], "security_groups": [{"name": "5aee7885-2e32-4898-97ed-140920174f50"}]}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:03:48.887 20837 DEBUG oslo_concurrency.lockutils [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:03:48.888 20837 DEBUG oslo_concurrency.lockutils [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:03:48.898 20837 DEBUG oslo_concurrency.lockutils [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:03:48.899 20837 DEBUG oslo_concurrency.lockutils [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:03:48.930 20837 WARNING nova.image.glance [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 15:03:51.890 20837 DEBUG nova.network.neutronv2.api [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] validate_networks() for [(u'ad8e4dfd-1ea8-440d-809d-b153de92fe01', None, None, None)] validate_networks /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1692
2018-09-28 15:03:52.278 20837 DEBUG nova.virt.hardware [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] emulator threads policy constraint: None get_emulator_threads_constraint /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1289
2018-09-28 15:03:52.307 20837 DEBUG nova.quota [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Getting quotas for project 8bef18ab502f4677940a913a5a7256ec. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 15:03:52.319 20837 DEBUG nova.quota [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Getting quotas for user 8346f77a389b4e73990ce091147f8a00 and project 8bef18ab502f4677940a913a5a7256ec. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 15:03:52.365 20837 DEBUG nova.quota [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Getting quotas for project 8bef18ab502f4677940a913a5a7256ec. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 15:03:52.373 20837 DEBUG nova.quota [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Getting quotas for user 8346f77a389b4e73990ce091147f8a00 and project 8bef18ab502f4677940a913a5a7256ec. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 15:03:52.407 20837 DEBUG nova.quota [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Getting quotas for project 8bef18ab502f4677940a913a5a7256ec. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 15:03:52.414 20837 DEBUG nova.quota [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Getting quotas for user 8346f77a389b4e73990ce091147f8a00 and project 8bef18ab502f4677940a913a5a7256ec. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 15:03:52.451 20837 DEBUG nova.context [req-da770e54-8e07-458b-916d-223d7ec5f19d - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),d6ebb650-317a-44ff-9b75-bd1a36697143(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-28 15:03:52.452 20837 DEBUG oslo_concurrency.lockutils [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:03:52.453 20837 DEBUG oslo_concurrency.lockutils [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:03:52.454 20837 DEBUG oslo_concurrency.lockutils [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:03:52.455 20837 DEBUG oslo_concurrency.lockutils [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:03:52.504 20837 DEBUG nova.quota [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Getting quotas for project 8bef18ab502f4677940a913a5a7256ec. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 15:03:52.514 20837 DEBUG nova.quota [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Getting quotas for user 8346f77a389b4e73990ce091147f8a00 and project 8bef18ab502f4677940a913a5a7256ec. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 15:03:52.537 20837 DEBUG nova.compute.api [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Going to run 1 instances... _provision_instances /usr/lib/python2.7/site-packages/nova/compute/api.py:891
2018-09-28 15:03:52.583 20837 DEBUG nova.compute.api [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='12a419bc-ac53-4807-ab39-866cafa926c2',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _bdm_validate_set_size_and_instance /usr/lib/python2.7/site-packages/nova/compute/api.py:1268
2018-09-28 15:03:52.821 20837 INFO nova.osapi_compute.wsgi.server [req-8ff28b02-a945-4930-b149-7923f23e1be0 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "POST /v2.1/8bef18ab502f4677940a913a5a7256ec/servers HTTP/1.1" status: 202 len: 989 time: 3.9903259
2018-09-28 15:03:52.852 20837 DEBUG nova.api.openstack.wsgi [req-e4a0b758-c772-4f85-9c0b-03f4d1330b8a 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:03:52.855 20837 DEBUG nova.compute.api [req-e4a0b758-c772-4f85-9c0b-03f4d1330b8a 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:03:52.924 20837 DEBUG nova.policy [req-e4a0b758-c772-4f85-9c0b-03f4d1330b8a 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:03:53.032 20837 INFO nova.osapi_compute.wsgi.server [req-e4a0b758-c772-4f85-9c0b-03f4d1330b8a 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957 HTTP/1.1" status: 200 len: 1857 time: 0.1915169
2018-09-28 15:03:53.120 20837 DEBUG nova.api.openstack.wsgi [req-5d0725e5-e1d2-4d79-ba47-930405cb0899 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f1e2cfd9090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:03:53.151 20837 INFO nova.osapi_compute.wsgi.server [req-5d0725e5-e1d2-4d79-ba47-930405cb0899 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0373678
2018-09-28 15:03:58.425 20842 DEBUG nova.osapi_compute.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20842) accepted ('10.0.20.23', 52782) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:03:58.438 20842 WARNING keystonemiddleware.auth_token [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-28 15:04:00.331 20842 INFO nova.osapi_compute.wsgi.server [req-a8d1a404-f6f1-4575-a73e-537600519b88 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec HTTP/1.1" status: 404 len: 382 time: 1.8997691
2018-09-28 15:04:00.346 20842 DEBUG nova.api.openstack.wsgi [req-86cd4e80-c29e-4cb4-aeea-3a26fd9b4488 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f1e2d04e4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:00.350 20842 INFO nova.osapi_compute.wsgi.server [req-86cd4e80-c29e-4cb4-aeea-3a26fd9b4488 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0117412
2018-09-28 15:04:00.718 20842 DEBUG nova.api.openstack.wsgi [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc98550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:00.731 20842 DEBUG nova.compute.api [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', u'name': u'tempest-INSTANCE_SAMPLE-1538161238'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:04:00.787 20842 DEBUG oslo_db.sqlalchemy.engines [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:00.833 20842 DEBUG oslo_concurrency.lockutils [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:00.835 20842 DEBUG oslo_concurrency.lockutils [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:00.860 20842 DEBUG oslo_db.sqlalchemy.engines [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:01.094 20842 DEBUG nova.compute.api [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),d6ebb650-317a-44ff-9b75-bd1a36697143(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-28 15:04:01.095 20842 DEBUG nova.compute.api [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:04:01.096 20842 DEBUG nova.compute.api [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:04:01.097 20842 DEBUG oslo_concurrency.lockutils [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:01.103 20842 DEBUG oslo_concurrency.lockutils [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:01.124 20842 DEBUG oslo_db.sqlalchemy.engines [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:01.241 20842 INFO nova.osapi_compute.wsgi.server [req-e04ee58f-4647-476a-9eeb-cddc72a9237f 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers?name=tempest-INSTANCE_SAMPLE-1538161238 HTTP/1.1" status: 200 len: 786 time: 0.5355351
2018-09-28 15:04:01.272 20842 DEBUG nova.api.openstack.wsgi [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:01.274 20842 DEBUG nova.compute.api [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:04:01.773 20842 DEBUG oslo_concurrency.lockutils [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:01.775 20842 DEBUG oslo_concurrency.lockutils [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:02.200 20842 DEBUG nova.objects.instance [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lazy-loading 'services' on Instance uuid c4b01437-0cd9-498f-b8e6-92a43c43e957 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-28 15:04:02.338 20842 DEBUG nova.policy [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:04:06.571 20842 INFO nova.osapi_compute.wsgi.server [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957 HTTP/1.1" status: 200 len: 2438 time: 5.3075161
2018-09-28 15:04:08.298 20842 DEBUG nova.osapi_compute.wsgi.server [req-046eedbc-0875-4e24-b55d-b80577ba7565 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20842) accepted ('10.0.20.23', 53924) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:08.710 20842 DEBUG nova.api.openstack.wsgi [req-2760955e-7d99-4d95-96dd-b6bdd8f39a8b 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f1e2ce1f810>>, body: {"events": [{"tag": "fa3104cc-c94a-4853-936d-a3bf316c6b97", "name": "network-changed", "server_uuid": "c4b01437-0cd9-498f-b8e6-92a43c43e957"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:04:08.736 20842 DEBUG oslo_concurrency.lockutils [req-2760955e-7d99-4d95-96dd-b6bdd8f39a8b 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:08.737 20842 DEBUG oslo_concurrency.lockutils [req-2760955e-7d99-4d95-96dd-b6bdd8f39a8b 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:08.772 20842 INFO nova.api.openstack.compute.server_external_events [req-2760955e-7d99-4d95-96dd-b6bdd8f39a8b 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Creating event network-changed:fa3104cc-c94a-4853-936d-a3bf316c6b97 for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 on localhost.localdomain
2018-09-28 15:04:09.001 20842 INFO nova.osapi_compute.wsgi.server [req-2760955e-7d99-4d95-96dd-b6bdd8f39a8b 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] 10.0.20.23 "POST /v2.1/368f193974e14846a186e2cbdb34d110/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 0.6966600
2018-09-28 15:04:13.212 20837 DEBUG nova.osapi_compute.wsgi.server [req-5d0725e5-e1d2-4d79-ba47-930405cb0899 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20837) accepted ('10.0.20.23', 53966) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:13.641 20837 DEBUG nova.api.openstack.wsgi [req-4ac15024-895c-46a0-82bc-2f522b10e120 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f1e2ce1f810>>, body: {"events": [{"status": "completed", "tag": "fa3104cc-c94a-4853-936d-a3bf316c6b97", "name": "network-vif-plugged", "server_uuid": "c4b01437-0cd9-498f-b8e6-92a43c43e957"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:04:13.667 20837 DEBUG oslo_concurrency.lockutils [req-4ac15024-895c-46a0-82bc-2f522b10e120 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:13.667 20837 DEBUG oslo_concurrency.lockutils [req-4ac15024-895c-46a0-82bc-2f522b10e120 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:13.699 20837 INFO nova.api.openstack.compute.server_external_events [req-4ac15024-895c-46a0-82bc-2f522b10e120 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Creating event network-vif-plugged:fa3104cc-c94a-4853-936d-a3bf316c6b97 for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 on localhost.localdomain
2018-09-28 15:04:13.753 20837 INFO nova.osapi_compute.wsgi.server [req-4ac15024-895c-46a0-82bc-2f522b10e120 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] 10.0.20.23 "POST /v2.1/368f193974e14846a186e2cbdb34d110/os-server-external-events HTTP/1.1" status: 200 len: 582 time: 0.5372510
2018-09-28 15:04:14.770 20835 DEBUG nova.osapi_compute.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20835) accepted ('10.0.20.23', 53996) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:14.789 20835 WARNING keystonemiddleware.auth_token [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-28 15:04:16.344 20835 INFO nova.osapi_compute.wsgi.server [req-d5f03f16-888f-4cf7-8568-7ffc0cee7cb1 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec HTTP/1.1" status: 404 len: 382 time: 1.5698290
2018-09-28 15:04:16.366 20835 DEBUG nova.api.openstack.wsgi [req-4964b7dd-b758-4a61-a81f-986c5a1f1526 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f1e2d04e4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:16.368 20835 INFO nova.osapi_compute.wsgi.server [req-4964b7dd-b758-4a61-a81f-986c5a1f1526 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0114510
2018-09-28 15:04:16.687 20835 DEBUG nova.api.openstack.wsgi [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc98550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:16.694 20835 DEBUG nova.compute.api [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', u'name': u'tempest-INSTANCE_SAMPLE-1538161238'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:04:16.729 20835 DEBUG oslo_db.sqlalchemy.engines [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:16.782 20835 DEBUG oslo_concurrency.lockutils [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:16.785 20835 DEBUG oslo_concurrency.lockutils [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:16.806 20835 DEBUG oslo_db.sqlalchemy.engines [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:16.910 20835 DEBUG nova.compute.api [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),d6ebb650-317a-44ff-9b75-bd1a36697143(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-28 15:04:16.911 20835 DEBUG nova.compute.api [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:04:16.912 20835 DEBUG nova.compute.api [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:04:16.914 20835 DEBUG oslo_concurrency.lockutils [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:16.919 20835 DEBUG oslo_concurrency.lockutils [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:16.941 20835 DEBUG oslo_db.sqlalchemy.engines [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:17.033 20835 INFO nova.osapi_compute.wsgi.server [req-747f2c75-9f34-4308-98cf-8079958f5278 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers?name=tempest-INSTANCE_SAMPLE-1538161238 HTTP/1.1" status: 200 len: 786 time: 0.3523209
2018-09-28 15:04:17.056 20835 DEBUG nova.api.openstack.wsgi [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:17.057 20835 DEBUG nova.compute.api [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:04:17.446 20835 DEBUG oslo_concurrency.lockutils [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:17.447 20835 DEBUG oslo_concurrency.lockutils [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:17.639 20835 DEBUG nova.objects.instance [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lazy-loading 'services' on Instance uuid c4b01437-0cd9-498f-b8e6-92a43c43e957 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-28 15:04:17.729 20835 DEBUG nova.policy [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:04:18.757 20835 INFO nova.osapi_compute.wsgi.server [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957 HTTP/1.1" status: 200 len: 2600 time: 1.7082479
2018-09-28 15:04:38.324 20857 DEBUG nova.metadata.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20857) accepted ('10.0.20.23', 54454) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:38.364 20857 DEBUG oslo_db.sqlalchemy.engines [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:38.399 20857 DEBUG oslo_concurrency.lockutils [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:38.411 20857 DEBUG oslo_concurrency.lockutils [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.012s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:38.429 20857 DEBUG oslo_db.sqlalchemy.engines [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:40.100 20857 WARNING oslo_config.cfg [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-28 15:04:40.103 20857 INFO nova.metadata.wsgi.server [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/instance-id HTTP/1.1" status: 200 len: 127 time: 1.7740631
2018-09-28 15:04:40.348 20861 DEBUG nova.metadata.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20861) accepted ('10.0.20.23', 54468) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:40.387 20861 DEBUG oslo_db.sqlalchemy.engines [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:40.430 20861 DEBUG oslo_concurrency.lockutils [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:40.435 20861 DEBUG oslo_concurrency.lockutils [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:40.456 20861 DEBUG oslo_db.sqlalchemy.engines [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:41.969 20861 WARNING oslo_config.cfg [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-28 15:04:41.972 20861 INFO nova.metadata.wsgi.server [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/public-keys HTTP/1.1" status: 200 len: 152 time: 1.6163580
2018-09-28 15:04:42.106 20857 DEBUG nova.metadata.wsgi.server [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] (20857) accepted ('10.0.20.23', 54480) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:42.108 20857 DEBUG nova.api.metadata.handler [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:42.110 20857 INFO nova.metadata.wsgi.server [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/public-keys/0/openssh-key HTTP/1.1" status: 200 len: 526 time: 0.0020661
2018-09-28 15:04:42.306 20857 DEBUG nova.metadata.wsgi.server [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] (20857) accepted ('10.0.20.23', 54482) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:42.308 20857 DEBUG nova.api.metadata.handler [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:42.310 20857 INFO nova.metadata.wsgi.server [req-4fdc7f4f-f9d6-46b7-94c0-efd9d9bb5896 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/instance-id HTTP/1.1" status: 200 len: 127 time: 0.0016279
2018-09-28 15:04:42.936 20842 DEBUG nova.osapi_compute.wsgi.server [req-2760955e-7d99-4d95-96dd-b6bdd8f39a8b 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] (20842) accepted ('10.0.20.23', 54146) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:43.191 20861 DEBUG nova.metadata.wsgi.server [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] (20861) accepted ('10.0.20.23', 54498) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:43.194 20861 DEBUG nova.api.metadata.handler [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:43.196 20861 INFO nova.metadata.wsgi.server [req-e743a7fa-82a7-47bf-95d9-3694eb180092 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/ami-launch-index HTTP/1.1" status: 200 len: 117 time: 0.0025051
2018-09-28 15:04:43.332 20842 DEBUG nova.api.openstack.wsgi [req-05adb863-e54d-4c9f-91ec-ddea4ba53469 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:43.334 20842 DEBUG nova.compute.api [req-05adb863-e54d-4c9f-91ec-ddea4ba53469 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1538161238 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-09-28 15:04:43.335 20842 INFO nova.api.openstack.wsgi [req-05adb863-e54d-4c9f-91ec-ddea4ba53469 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] HTTP exception thrown: Instance tempest-INSTANCE_SAMPLE-1538161238 could not be found.
2018-09-28 15:04:43.336 20842 DEBUG nova.api.openstack.wsgi [req-05adb863-e54d-4c9f-91ec-ddea4ba53469 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Returning 404 to user: Instance tempest-INSTANCE_SAMPLE-1538161238 could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-28 15:04:43.339 20842 INFO nova.osapi_compute.wsgi.server [req-05adb863-e54d-4c9f-91ec-ddea4ba53469 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/tempest-INSTANCE_SAMPLE-1538161238 HTTP/1.1" status: 404 len: 530 time: 0.4008169
2018-09-28 15:04:43.365 20842 DEBUG nova.api.openstack.wsgi [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc98550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:43.367 20842 DEBUG nova.compute.api [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', u'name': u'tempest-INSTANCE_SAMPLE-1538161238'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:04:43.380 20842 DEBUG oslo_concurrency.lockutils [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:43.381 20842 DEBUG oslo_concurrency.lockutils [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:43.435 20842 DEBUG nova.compute.api [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:04:43.436 20842 DEBUG nova.compute.api [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:04:43.437 20842 DEBUG oslo_concurrency.lockutils [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:43.438 20842 DEBUG oslo_concurrency.lockutils [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:43.437 20856 DEBUG nova.metadata.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20856) accepted ('10.0.20.23', 54502) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:43.484 20856 DEBUG oslo_db.sqlalchemy.engines [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:43.500 20842 INFO nova.osapi_compute.wsgi.server [req-582c1c24-d608-4213-a341-4531baa09e8d 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers?name=tempest-INSTANCE_SAMPLE-1538161238 HTTP/1.1" status: 200 len: 784 time: 0.1423950
2018-09-28 15:04:43.522 20842 DEBUG nova.api.openstack.wsgi [req-93144fc2-ba27-4d0f-a7f6-6b9a3759f089 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:43.523 20842 DEBUG nova.compute.api [req-93144fc2-ba27-4d0f-a7f6-6b9a3759f089 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:04:43.534 20856 DEBUG oslo_concurrency.lockutils [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:43.535 20842 DEBUG oslo_concurrency.lockutils [req-93144fc2-ba27-4d0f-a7f6-6b9a3759f089 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:43.536 20842 DEBUG oslo_concurrency.lockutils [req-93144fc2-ba27-4d0f-a7f6-6b9a3759f089 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:43.540 20856 DEBUG oslo_concurrency.lockutils [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:43.563 20856 DEBUG oslo_db.sqlalchemy.engines [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:43.635 20842 DEBUG nova.policy [req-93144fc2-ba27-4d0f-a7f6-6b9a3759f089 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:04:44.194 20842 INFO nova.osapi_compute.wsgi.server [req-93144fc2-ba27-4d0f-a7f6-6b9a3759f089 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957 HTTP/1.1" status: 200 len: 2207 time: 0.6776671
2018-09-28 15:04:44.213 20842 DEBUG nova.api.openstack.wsgi [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Action: 'action', calling method: <function version_select at 0x7f1e2cbc1b18>, body: {"addFloatingIp": {"address": "172.24.4.9"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:04:44.215 20842 DEBUG nova.compute.api [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:04:44.225 20842 DEBUG oslo_concurrency.lockutils [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:44.226 20842 DEBUG oslo_concurrency.lockutils [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:44.287 20842 DEBUG oslo_concurrency.lockutils [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Acquired semaphore "refresh_cache-c4b01437-0cd9-498f-b8e6-92a43c43e957" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-28 15:04:45.064 20856 WARNING oslo_config.cfg [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-28 15:04:45.067 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/instance-type HTTP/1.1" status: 200 len: 123 time: 1.6231301
2018-09-28 15:04:45.687 20842 DEBUG nova.network.neutronv2.api [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1315
2018-09-28 15:04:45.901 20856 DEBUG nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] (20856) accepted ('10.0.20.23', 54538) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:45.905 20856 DEBUG nova.api.metadata.handler [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:45.906 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/local-ipv4 HTTP/1.1" status: 200 len: 128 time: 0.0025480
2018-09-28 15:04:46.194 20858 DEBUG nova.metadata.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20858) accepted ('10.0.20.23', 54540) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:46.247 20858 DEBUG oslo_db.sqlalchemy.engines [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:46.305 20858 DEBUG oslo_concurrency.lockutils [req-d99b7337-adf4-48ab-90d4-8f35d660e150 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:46.312 20858 DEBUG oslo_concurrency.lockutils [req-d99b7337-adf4-48ab-90d4-8f35d660e150 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.008s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:46.335 20858 DEBUG oslo_db.sqlalchemy.engines [req-d99b7337-adf4-48ab-90d4-8f35d660e150 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:46.688 20835 DEBUG nova.osapi_compute.wsgi.server [req-ef686c45-5454-4a26-8e2c-c3c4ffb68572 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20835) accepted ('10.0.20.23', 54210) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:47.152 20835 DEBUG nova.api.openstack.wsgi [req-9ee603a0-f96b-42c5-be77-4d0577c59fb7 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f1e2ce1f810>>, body: {"events": [{"tag": "fa3104cc-c94a-4853-936d-a3bf316c6b97", "name": "network-changed", "server_uuid": "c4b01437-0cd9-498f-b8e6-92a43c43e957"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:04:47.162 20835 DEBUG oslo_concurrency.lockutils [req-9ee603a0-f96b-42c5-be77-4d0577c59fb7 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:47.163 20835 DEBUG oslo_concurrency.lockutils [req-9ee603a0-f96b-42c5-be77-4d0577c59fb7 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:47.187 20835 INFO nova.api.openstack.compute.server_external_events [req-9ee603a0-f96b-42c5-be77-4d0577c59fb7 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] Creating event network-changed:fa3104cc-c94a-4853-936d-a3bf316c6b97 for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 on localhost.localdomain
2018-09-28 15:04:47.347 20835 INFO nova.osapi_compute.wsgi.server [req-9ee603a0-f96b-42c5-be77-4d0577c59fb7 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] 10.0.20.23 "POST /v2.1/368f193974e14846a186e2cbdb34d110/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 0.6575911
2018-09-28 15:04:47.760 20842 DEBUG nova.network.base_api [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "fa3104cc-c94a-4853-936d-a3bf316c6b97", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [{"meta": {}, "version": 4, "type": "floating", "address": "172.24.4.9"}], "address": "11.153.1.10"}], "version": 4, "meta": {"dhcp_server": "11.153.1.2"}, "dns": [{"meta": {}, "version": 4, "type": "dns", "address": "8.8.4.4"}], "routes": [], "cidr": "11.153.1.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "11.153.1.1"}}], "meta": {"injected": false, "tenant_id": "8bef18ab502f4677940a913a5a7256ec", "mtu": 1450}, "id": "ad8e4dfd-1ea8-440d-809d-b153de92fe01", "label": "tempest-private-1538161238"}, "devname": "tapfa3104cc-c9", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "datapath_type": "system", "ovs_hybrid_plug": true}, "address": "fa:16:3e:7c:37:b5", "active": true, "type": "ovs", "id": "fa3104cc-c94a-4853-936d-a3bf316c6b97", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2018-09-28 15:04:47.789 20842 DEBUG oslo_concurrency.lockutils [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Releasing semaphore "refresh_cache-c4b01437-0cd9-498f-b8e6-92a43c43e957" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-28 15:04:47.790 20842 INFO nova.osapi_compute.wsgi.server [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "POST /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957/action HTTP/1.1" status: 202 len: 411 time: 3.5833199
2018-09-28 15:04:48.072 20858 WARNING oslo_config.cfg [req-d99b7337-adf4-48ab-90d4-8f35d660e150 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-28 15:04:48.075 20858 INFO nova.metadata.wsgi.server [req-d99b7337-adf4-48ab-90d4-8f35d660e150 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/public-ipv4 HTTP/1.1" status: 200 len: 116 time: 1.8750231
2018-09-28 15:04:48.866 20856 DEBUG nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] (20856) accepted ('10.0.20.23', 54584) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:48.868 20856 DEBUG nova.api.metadata.handler [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:48.869 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/hostname HTTP/1.1" status: 200 len: 161 time: 0.0014780
2018-09-28 15:04:49.329 20856 DEBUG nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] (20856) accepted ('10.0.20.23', 54590) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:49.331 20856 DEBUG nova.api.metadata.handler [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:49.332 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/local-hostname HTTP/1.1" status: 200 len: 161 time: 0.0014610
2018-09-28 15:04:49.517 20856 DEBUG nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] (20856) accepted ('10.0.20.23', 54592) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:49.518 20856 DEBUG nova.api.metadata.handler [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:49.520 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/user-data HTTP/1.1" status: 404 len: 176 time: 0.0022650
2018-09-28 15:04:49.749 20856 DEBUG nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] (20856) accepted ('10.0.20.23', 54594) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:49.751 20856 DEBUG nova.api.metadata.handler [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:49.752 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/block-device-mapping HTTP/1.1" status: 200 len: 124 time: 0.0018179
2018-09-28 15:04:50.476 20855 DEBUG nova.metadata.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20855) accepted ('10.0.20.23', 54604) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:50.514 20855 DEBUG oslo_db.sqlalchemy.engines [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:50.551 20855 DEBUG oslo_concurrency.lockutils [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:50.557 20855 DEBUG oslo_concurrency.lockutils [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:50.578 20855 DEBUG oslo_db.sqlalchemy.engines [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:51.992 20855 WARNING oslo_config.cfg [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-28 15:04:51.995 20855 INFO nova.metadata.wsgi.server [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/block-device-mapping/ami HTTP/1.1" status: 200 len: 119 time: 1.5132658
2018-09-28 15:04:52.955 20855 DEBUG nova.metadata.wsgi.server [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] (20855) accepted ('10.0.20.23', 54622) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:52.958 20855 DEBUG nova.api.metadata.handler [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:52.959 20855 INFO nova.metadata.wsgi.server [req-01bd6917-e352-4948-b2aa-7e5b27bfcc11 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/block-device-mapping/root HTTP/1.1" status: 200 len: 124 time: 0.0014021
2018-09-28 15:04:53.784 20856 DEBUG nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] (20856) accepted ('10.0.20.23', 54634) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:53.787 20856 DEBUG nova.api.metadata.handler [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] Using cached metadata for instance c4b01437-0cd9-498f-b8e6-92a43c43e957 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-28 15:04:53.789 20856 INFO nova.metadata.wsgi.server [req-7bcf1e2d-e44a-41a2-9e29-ad42aabe4170 - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/public-hostname HTTP/1.1" status: 200 len: 161 time: 0.0025909
2018-09-28 15:04:54.032 20853 DEBUG nova.metadata.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20853) accepted ('10.0.20.23', 54636) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:54.084 20853 DEBUG oslo_db.sqlalchemy.engines [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:54.129 20853 DEBUG oslo_concurrency.lockutils [req-de5e4a03-7618-4e11-9d50-ec93f5d03cad - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:54.135 20853 DEBUG oslo_concurrency.lockutils [req-de5e4a03-7618-4e11-9d50-ec93f5d03cad - - - - -] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:54.153 20853 DEBUG oslo_db.sqlalchemy.engines [req-de5e4a03-7618-4e11-9d50-ec93f5d03cad - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:55.780 20853 WARNING oslo_config.cfg [req-de5e4a03-7618-4e11-9d50-ec93f5d03cad - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-28 15:04:55.786 20853 INFO nova.metadata.wsgi.server [req-de5e4a03-7618-4e11-9d50-ec93f5d03cad - - - - -] 11.153.1.10,10.0.20.23 "GET /2009-04-04/meta-data/placement/availability-zone HTTP/1.1" status: 200 len: 120 time: 1.7458870
2018-09-28 15:04:57.097 20838 DEBUG nova.osapi_compute.wsgi.server [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] (20838) accepted ('10.0.20.23', 54306) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:04:57.114 20838 WARNING keystonemiddleware.auth_token [req-37751b11-1912-42df-9ca4-c5bc15ccec7c - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-28 15:04:58.626 20838 INFO nova.osapi_compute.wsgi.server [req-7f494a32-a243-46a3-9402-b3100edb08b2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec HTTP/1.1" status: 404 len: 382 time: 1.5213199
2018-09-28 15:04:58.644 20838 DEBUG nova.api.openstack.wsgi [req-10c4c3e1-fa16-4453-a2f4-e8eaaea2c1dd 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f1e2d04e4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:58.647 20838 INFO nova.osapi_compute.wsgi.server [req-10c4c3e1-fa16-4453-a2f4-e8eaaea2c1dd 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0104692
2018-09-28 15:04:58.910 20838 DEBUG nova.api.openstack.wsgi [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:04:58.916 20838 DEBUG nova.compute.api [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:04:58.949 20838 DEBUG oslo_db.sqlalchemy.engines [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:58.996 20838 DEBUG oslo_concurrency.lockutils [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:58.998 20838 DEBUG oslo_concurrency.lockutils [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:59.020 20838 DEBUG oslo_db.sqlalchemy.engines [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:59.157 20838 DEBUG nova.compute.api [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),d6ebb650-317a-44ff-9b75-bd1a36697143(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-28 15:04:59.158 20838 DEBUG nova.compute.api [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:04:59.158 20838 DEBUG nova.compute.api [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:04:59.160 20838 DEBUG oslo_concurrency.lockutils [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:59.166 20838 DEBUG oslo_concurrency.lockutils [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:59.183 20838 DEBUG oslo_db.sqlalchemy.engines [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 15:04:59.874 20838 DEBUG oslo_concurrency.lockutils [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:04:59.877 20838 DEBUG oslo_concurrency.lockutils [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:04:59.910 20838 DEBUG nova.policy [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:05:03.625 20838 INFO nova.osapi_compute.wsgi.server [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2720 time: 4.7221150
2018-09-28 15:05:19.984 20837 DEBUG nova.api.openstack.wsgi [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:05:20.005 20837 DEBUG nova.compute.api [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 28, 19, 0, 21, 592917, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:05:20.068 20837 DEBUG oslo_concurrency.lockutils [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:20.069 20837 DEBUG oslo_concurrency.lockutils [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:20.180 20837 DEBUG nova.compute.api [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:05:20.181 20837 DEBUG nova.compute.api [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:05:20.183 20837 DEBUG oslo_concurrency.lockutils [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:20.183 20837 DEBUG oslo_concurrency.lockutils [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:20.377 20837 DEBUG oslo_concurrency.lockutils [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:20.379 20837 DEBUG oslo_concurrency.lockutils [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:20.393 20837 DEBUG nova.policy [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'd620094bd6d047979241572f64ecaca7', 'roles': [u'admin', u'ResellerAdmin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'368f193974e14846a186e2cbdb34d110', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:05:20.831 20837 INFO nova.osapi_compute.wsgi.server [req-35d7b50b-e520-435a-9260-e45021e358b6 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] 10.0.20.23 "GET /v2.1/368f193974e14846a186e2cbdb34d110/servers/detail?all_tenants=True&changes-since=2018-09-28T19%3A00%3A21.592917%2B00%3A00 HTTP/1.1" status: 200 len: 2327 time: 0.8971550
2018-09-28 15:05:22.990 20838 DEBUG nova.osapi_compute.wsgi.server [req-c0b6e6ba-ab1e-4e43-b060-0af36dfebcca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20838) accepted ('10.0.20.23', 55448) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:05:23.402 20838 DEBUG nova.api.openstack.wsgi [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:05:23.405 20838 DEBUG nova.compute.api [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:05:23.422 20838 DEBUG oslo_concurrency.lockutils [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:23.423 20838 DEBUG oslo_concurrency.lockutils [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:23.489 20838 DEBUG nova.compute.api [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:05:23.489 20838 DEBUG nova.compute.api [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:05:23.490 20838 DEBUG oslo_concurrency.lockutils [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:23.491 20838 DEBUG oslo_concurrency.lockutils [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:23.592 20838 DEBUG oslo_concurrency.lockutils [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:23.592 20838 DEBUG oslo_concurrency.lockutils [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:23.602 20838 DEBUG nova.policy [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:05:24.206 20838 INFO nova.osapi_compute.wsgi.server [req-23be0c7b-a80d-4e55-920f-551d2b1a93ca 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2327 time: 1.2131770
2018-09-28 15:05:34.314 20835 DEBUG nova.osapi_compute.wsgi.server [req-9ee603a0-f96b-42c5-be77-4d0577c59fb7 4e52bdcf022b4eea9cd7e3a3cb46b142 368f193974e14846a186e2cbdb34d110 - default default] (20835) accepted ('10.0.20.23', 55520) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:05:34.662 20835 DEBUG nova.api.openstack.wsgi [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:05:34.665 20835 DEBUG nova.compute.api [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:05:34.682 20835 DEBUG oslo_concurrency.lockutils [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:34.683 20835 DEBUG oslo_concurrency.lockutils [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:34.756 20835 DEBUG nova.compute.api [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:05:34.757 20835 DEBUG nova.compute.api [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:05:34.758 20835 DEBUG oslo_concurrency.lockutils [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:34.759 20835 DEBUG oslo_concurrency.lockutils [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:34.867 20835 DEBUG oslo_concurrency.lockutils [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:34.868 20835 DEBUG oslo_concurrency.lockutils [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:34.883 20835 DEBUG nova.policy [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:05:35.378 20835 INFO nova.osapi_compute.wsgi.server [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2327 time: 1.0611479
2018-09-28 15:05:47.217 20840 DEBUG nova.osapi_compute.wsgi.server [req-a43a27a1-b2dc-44fb-8e81-270d21263c89 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20840) accepted ('10.0.20.23', 55570) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:05:47.711 20840 DEBUG nova.api.openstack.wsgi [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:05:47.809 20840 DEBUG nova.compute.api [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:05:47.894 20840 DEBUG oslo_concurrency.lockutils [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:47.895 20840 DEBUG oslo_concurrency.lockutils [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.010s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:47.985 20840 DEBUG nova.compute.api [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:05:47.986 20840 DEBUG nova.compute.api [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:05:47.987 20840 DEBUG oslo_concurrency.lockutils [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:47.987 20840 DEBUG oslo_concurrency.lockutils [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:48.155 20840 DEBUG oslo_concurrency.lockutils [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:48.156 20840 DEBUG oslo_concurrency.lockutils [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:48.173 20840 DEBUG nova.policy [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:05:49.328 20840 INFO nova.osapi_compute.wsgi.server [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2327 time: 2.1087570
2018-09-28 15:05:55.931 20837 DEBUG nova.api.openstack.wsgi [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:05:55.936 20837 DEBUG nova.compute.api [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 28, 19, 0, 57, 299651, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:05:55.951 20837 DEBUG oslo_concurrency.lockutils [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:55.952 20837 DEBUG oslo_concurrency.lockutils [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:56.028 20837 DEBUG nova.compute.api [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:05:56.029 20837 DEBUG nova.compute.api [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:05:56.030 20837 DEBUG oslo_concurrency.lockutils [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:56.031 20837 DEBUG oslo_concurrency.lockutils [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:56.146 20837 DEBUG oslo_concurrency.lockutils [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:05:56.147 20837 DEBUG oslo_concurrency.lockutils [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:05:56.162 20837 DEBUG nova.policy [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'd620094bd6d047979241572f64ecaca7', 'roles': [u'admin', u'ResellerAdmin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'368f193974e14846a186e2cbdb34d110', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:05:56.906 20837 INFO nova.osapi_compute.wsgi.server [req-e7fe810e-01f6-4c01-8896-7cd9fbdc78a7 d620094bd6d047979241572f64ecaca7 368f193974e14846a186e2cbdb34d110 - default default] 10.0.20.23 "GET /v2.1/368f193974e14846a186e2cbdb34d110/servers/detail?all_tenants=True&changes-since=2018-09-28T19%3A00%3A57.299651%2B00%3A00 HTTP/1.1" status: 200 len: 2327 time: 0.9843118
2018-09-28 15:06:04.897 20840 DEBUG nova.osapi_compute.wsgi.server [req-f98524aa-ee6c-4045-ad0e-7dc080d1f335 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20840) accepted ('10.0.20.23', 56662) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:06:05.381 20840 DEBUG nova.api.openstack.wsgi [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:06:05.383 20840 DEBUG nova.compute.api [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:06:05.399 20840 DEBUG oslo_concurrency.lockutils [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:05.400 20840 DEBUG oslo_concurrency.lockutils [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:05.483 20840 DEBUG nova.compute.api [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:06:05.484 20840 DEBUG nova.compute.api [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:06:05.485 20840 DEBUG oslo_concurrency.lockutils [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:05.486 20840 DEBUG oslo_concurrency.lockutils [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:05.606 20840 DEBUG oslo_concurrency.lockutils [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:05.607 20840 DEBUG oslo_concurrency.lockutils [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:05.621 20840 DEBUG nova.policy [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:06:06.344 20840 INFO nova.osapi_compute.wsgi.server [req-b6a8edfa-79c3-4dad-b0b9-189b70068281 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2327 time: 1.4416380
2018-09-28 15:06:22.572 20835 DEBUG nova.osapi_compute.wsgi.server [req-7cdf2827-5e16-4dfc-a180-2a0980dcb7c2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20835) accepted ('10.0.20.23', 56690) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:06:23.026 20835 DEBUG nova.api.openstack.wsgi [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:06:23.028 20835 DEBUG nova.compute.api [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:06:23.044 20835 DEBUG oslo_concurrency.lockutils [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:23.045 20835 DEBUG oslo_concurrency.lockutils [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:23.111 20835 DEBUG nova.compute.api [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:06:23.111 20835 DEBUG nova.compute.api [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:06:23.112 20835 DEBUG oslo_concurrency.lockutils [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:23.113 20835 DEBUG oslo_concurrency.lockutils [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:23.248 20835 DEBUG oslo_concurrency.lockutils [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:23.249 20835 DEBUG oslo_concurrency.lockutils [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:23.270 20835 DEBUG nova.policy [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:06:24.006 20835 INFO nova.osapi_compute.wsgi.server [req-7837f199-f85c-4f0d-9813-1eb78f5d231b 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2327 time: 1.4312768
2018-09-28 15:06:41.143 20842 DEBUG nova.osapi_compute.wsgi.server [req-b1691a65-c886-49de-9fb5-b1bb9bd63b23 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] (20842) accepted ('10.0.20.23', 56762) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:06:41.650 20842 DEBUG nova.api.openstack.wsgi [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc4f690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:06:41.654 20842 DEBUG nova.compute.api [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:06:41.675 20842 DEBUG oslo_concurrency.lockutils [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:41.677 20842 DEBUG oslo_concurrency.lockutils [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:41.787 20842 DEBUG nova.compute.api [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:06:41.788 20842 DEBUG nova.compute.api [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:06:41.789 20842 DEBUG oslo_concurrency.lockutils [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:41.790 20842 DEBUG oslo_concurrency.lockutils [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:41.936 20842 DEBUG oslo_concurrency.lockutils [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:41.938 20842 DEBUG oslo_concurrency.lockutils [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:41.953 20842 DEBUG nova.policy [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:06:42.667 20842 INFO nova.osapi_compute.wsgi.server [req-c34ecf39-f3a1-4f4a-b23c-579a835defd4 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/detail HTTP/1.1" status: 200 len: 2327 time: 1.5229750
2018-09-28 15:06:51.583 20836 DEBUG nova.osapi_compute.wsgi.server [req-332d542e-6773-46f4-b405-a6e04ce52f6d d5ce6e22423945b3856059aa9d9f9c35 24a4048b7dbb4950873e581bf0067256 - default default] (20836) accepted ('10.0.20.23', 56782) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-28 15:06:51.848 20836 DEBUG nova.api.openstack.wsgi [req-1b0e63a1-992b-40f3-bba6-ee0f9d6b6a03 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:06:51.851 20836 DEBUG nova.compute.api [req-1b0e63a1-992b-40f3-bba6-ee0f9d6b6a03 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1538161238 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-09-28 15:06:51.852 20836 INFO nova.api.openstack.wsgi [req-1b0e63a1-992b-40f3-bba6-ee0f9d6b6a03 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] HTTP exception thrown: Instance tempest-INSTANCE_SAMPLE-1538161238 could not be found.
2018-09-28 15:06:51.854 20836 DEBUG nova.api.openstack.wsgi [req-1b0e63a1-992b-40f3-bba6-ee0f9d6b6a03 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Returning 404 to user: Instance tempest-INSTANCE_SAMPLE-1538161238 could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-28 15:06:51.857 20836 INFO nova.osapi_compute.wsgi.server [req-1b0e63a1-992b-40f3-bba6-ee0f9d6b6a03 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/tempest-INSTANCE_SAMPLE-1538161238 HTTP/1.1" status: 404 len: 530 time: 0.2710280
2018-09-28 15:06:51.880 20836 DEBUG nova.api.openstack.wsgi [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cc98550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:06:51.884 20836 DEBUG nova.compute.api [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Searching by: {'deleted': False, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', u'name': u'tempest-INSTANCE_SAMPLE-1538161238'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-28 15:06:51.910 20836 DEBUG oslo_concurrency.lockutils [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:51.911 20836 DEBUG oslo_concurrency.lockutils [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:51.984 20836 DEBUG nova.compute.api [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-28 15:06:51.985 20836 DEBUG nova.compute.api [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Listing 1000 instances in cell d6ebb650-317a-44ff-9b75-bd1a36697143(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-28 15:06:51.987 20836 DEBUG oslo_concurrency.lockutils [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:51.988 20836 DEBUG oslo_concurrency.lockutils [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:52.075 20836 INFO nova.osapi_compute.wsgi.server [req-5099ea01-a134-4a50-b4e7-a7ca2c85f09e 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers?name=tempest-INSTANCE_SAMPLE-1538161238 HTTP/1.1" status: 200 len: 784 time: 0.2007351
2018-09-28 15:06:52.100 20836 DEBUG nova.api.openstack.wsgi [req-13f814da-7f8f-4982-8e09-546b751d1ea2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f1e2cb6f9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-28 15:06:52.102 20836 DEBUG nova.compute.api [req-13f814da-7f8f-4982-8e09-546b751d1ea2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:06:52.124 20836 DEBUG oslo_concurrency.lockutils [req-13f814da-7f8f-4982-8e09-546b751d1ea2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:52.124 20836 DEBUG oslo_concurrency.lockutils [req-13f814da-7f8f-4982-8e09-546b751d1ea2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:52.330 20836 DEBUG nova.policy [req-13f814da-7f8f-4982-8e09-546b751d1ea2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'8346f77a389b4e73990ce091147f8a00', 'roles': [u'admin'], 'user_domain_id': u'3ba8d95a35e54870a01b735f085e2858', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'8bef18ab502f4677940a913a5a7256ec', 'project_domain_id': u'3ba8d95a35e54870a01b735f085e2858'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-28 15:06:53.475 20836 INFO nova.osapi_compute.wsgi.server [req-13f814da-7f8f-4982-8e09-546b751d1ea2 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "GET /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957 HTTP/1.1" status: 200 len: 2324 time: 1.3830810
2018-09-28 15:06:53.966 20836 DEBUG nova.api.openstack.wsgi [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Action: 'create', calling method: <bound method VolumeAttachmentController.create of <nova.api.openstack.compute.volumes.VolumeAttachmentController object at 0x7f1e2cacfa90>>, body: {"volumeAttachment": {"device": "/dev/vdb", "volumeId": "5e1d571e-199e-4106-8b0e-2e76ed7068d1"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-28 15:06:53.969 20836 DEBUG nova.compute.api [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] [instance: c4b01437-0cd9-498f-b8e6-92a43c43e957] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-28 15:06:53.978 20836 DEBUG oslo_concurrency.lockutils [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 15:06:53.979 20836 DEBUG oslo_concurrency.lockutils [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 15:06:54.507 20836 WARNING nova.volume.cinder [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] The support for the Cinder API v2 is deprecated, please upgrade to Cinder API v3.
2018-09-28 15:06:54.535 20836 DEBUG cinderclient.v2.client [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] REQ: curl -g -i -X GET http://10.0.20.23:8776/v2/8bef18ab502f4677940a913a5a7256ec/volumes/5e1d571e-199e-4106-8b0e-2e76ed7068d1 -H "X-Service-Token: {SHA1}1af72d980beda207888edd7e5a806479552b3ed2" -H "User-Agent: python-cinderclient" -H "X-OpenStack-Request-ID: req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}5cecb705858cc394e44dabc96f2d6ee52e1a4ea3" _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:375
2018-09-28 15:06:55.058 20836 DEBUG cinderclient.v2.client [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] RESP: [200] X-Compute-Request-Id: req-4667a2af-98a5-4e75-9e6a-2fb4db25e34c Content-Type: application/json Content-Length: 1019 X-Openstack-Request-Id: req-4667a2af-98a5-4e75-9e6a-2fb4db25e34c Date: Fri, 28 Sep 2018 19:06:55 GMT Connection: keep-alive 
RESP BODY: {"volume": {"migration_status": null, "attachments": [], "links": [{"href": "http://10.0.20.23:8776/v2/8bef18ab502f4677940a913a5a7256ec/volumes/5e1d571e-199e-4106-8b0e-2e76ed7068d1", "rel": "self"}, {"href": "http://10.0.20.23:8776/8bef18ab502f4677940a913a5a7256ec/volumes/5e1d571e-199e-4106-8b0e-2e76ed7068d1", "rel": "bookmark"}], "availability_zone": "nova", "os-vol-host-attr:host": null, "encrypted": false, "updated_at": "2018-09-28T19:05:49.000000", "replication_status": null, "snapshot_id": null, "id": "5e1d571e-199e-4106-8b0e-2e76ed7068d1", "size": 1, "user_id": "8346f77a389b4e73990ce091147f8a00", "os-vol-tenant-attr:tenant_id": "8bef18ab502f4677940a913a5a7256ec", "os-vol-mig-status-attr:migstat": null, "metadata": {}, "status": "error", "description": null, "multiattach": false, "source_volid": null, "consistencygroup_id": null, "os-vol-mig-status-attr:name_id": null, "name": "tempest-VOLUME_SAMPLE-1538161238", "bootable": "true", "created_at": "2018-09-28T19:05:16.000000", "volume_type": "iscsi"}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:423
2018-09-28 15:06:55.059 20836 DEBUG cinderclient.v2.client [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] GET call to cinderv2 for http://10.0.20.23:8776/v2/8bef18ab502f4677940a913a5a7256ec/volumes/5e1d571e-199e-4106-8b0e-2e76ed7068d1 used request id req-4667a2af-98a5-4e75-9e6a-2fb4db25e34c request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:727
2018-09-28 15:06:55.063 20836 WARNING nova.volume.cinder [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] The support for the Cinder API v2 is deprecated, please upgrade to Cinder API v3.
2018-09-28 15:06:55.068 20836 DEBUG cinderclient.v2.client [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] REQ: curl -g -i -X POST http://10.0.20.23:8776/v2/8bef18ab502f4677940a913a5a7256ec/volumes/5e1d571e-199e-4106-8b0e-2e76ed7068d1/action -H "X-Service-Token: {SHA1}1af72d980beda207888edd7e5a806479552b3ed2" -H "Accept: application/json" -H "User-Agent: python-cinderclient" -H "X-Auth-Token: {SHA1}5cecb705858cc394e44dabc96f2d6ee52e1a4ea3" -H "Content-Type: application/json" -H "X-OpenStack-Request-ID: req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c" -d '{"os-reserve": null}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:375
2018-09-28 15:06:55.161 20836 DEBUG cinderclient.v2.client [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] RESP: [400] Content-Length: 128 Content-Type: application/json X-Compute-Request-Id: req-c42540be-04bc-4a25-8b03-70090ed78333 X-Openstack-Request-Id: req-c42540be-04bc-4a25-8b03-70090ed78333 Date: Fri, 28 Sep 2018 19:06:55 GMT Connection: keep-alive 
RESP BODY: {"badRequest": {"message": "Invalid volume: Volume status must be available to reserve, but the status is error.", "code": 400}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:423
2018-09-28 15:06:55.162 20836 DEBUG cinderclient.v2.client [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] POST call to cinderv2 for http://10.0.20.23:8776/v2/8bef18ab502f4677940a913a5a7256ec/volumes/5e1d571e-199e-4106-8b0e-2e76ed7068d1/action used request id req-c42540be-04bc-4a25-8b03-70090ed78333 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:727
2018-09-28 15:06:55.186 20836 INFO nova.api.openstack.wsgi [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] HTTP exception thrown: Invalid input received: Invalid volume: Volume status must be available to reserve, but the status is error. (HTTP 400) (Request-ID: req-c42540be-04bc-4a25-8b03-70090ed78333)
2018-09-28 15:06:55.187 20836 DEBUG nova.api.openstack.wsgi [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] Returning 400 to user: Invalid input received: Invalid volume: Volume status must be available to reserve, but the status is error. (HTTP 400) (Request-ID: req-c42540be-04bc-4a25-8b03-70090ed78333) __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-28 15:06:55.190 20836 INFO nova.osapi_compute.wsgi.server [req-5ab323d2-e2df-40ae-9abc-fc72dd23f08c 8346f77a389b4e73990ce091147f8a00 8bef18ab502f4677940a913a5a7256ec - 3ba8d95a35e54870a01b735f085e2858 3ba8d95a35e54870a01b735f085e2858] 10.0.20.23 "POST /v2.1/8bef18ab502f4677940a913a5a7256ec/servers/c4b01437-0cd9-498f-b8e6-92a43c43e957/os-volume_attachments HTTP/1.1" status: 400 len: 641 time: 1.2304502
