2018-09-28 21:16:22.278 30835 DEBUG oslo_db.sqlalchemy.engines [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 21:16:27.699 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 21:16:27.713 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.014s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 21:16:27.799 30835 DEBUG oslo_db.sqlalchemy.engines [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 21:16:28.162 30835 DEBUG nova.context [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-28 21:16:28.164 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 21:16:28.166 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 21:16:28.168 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 21:16:28.169 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 21:16:28.209 30835 DEBUG oslo_db.sqlalchemy.engines [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 21:16:28.249 30835 DEBUG nova.quota [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Getting quotas for project 066725ed2ca74d91a7d011ded7f87507. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 21:16:28.259 30835 DEBUG nova.quota [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Getting quotas for user fc329754a60f4445a75929df7a4babc3 and project 066725ed2ca74d91a7d011ded7f87507. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 21:16:28.283 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 21:16:28.284 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 21:16:28.285 30835 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:28.368 30835 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 21:16:28.375 30835 DEBUG nova.objects.instance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lazy-loading 'tags' on Instance uuid 16226d6f-c5a2-4eab-bad0-3a5ac5187753 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-28 21:16:28.459 30835 DEBUG nova.conductor.manager [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] [instance: 16226d6f-c5a2-4eab-bad0-3a5ac5187753] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='8c1afaf1-71c1-47a7-bde7-e10367999f23',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _create_block_device_mapping /usr/lib/python2.7/site-packages/nova/conductor/manager.py:968
2018-09-28 21:16:28.466 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 21:16:28.468 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 21:16:28.597 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 21:16:28.598 30835 DEBUG oslo_concurrency.lockutils [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 21:16:28.981 30830 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:29.055 30830 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 21:16:29.480 30829 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:29.560 30829 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 21:16:30.580 30832 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:30.651 30832 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 21:16:31.070 30836 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:31.160 30836 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 21:16:31.549 30833 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:31.646 30833 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 21:16:46.948 30832 WARNING nova.image.glance [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 21:16:46.981 30832 DEBUG nova.notifications.objects.base [req-e93d5692-edc0-4cb8-be98-484ed4351936 fc329754a60f4445a75929df7a4babc3 066725ed2ca74d91a7d011ded7f87507 - 4aa019171993410ba97fee324d963e72 4aa019171993410ba97fee324d963e72] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
