2018-09-14 01:06:07.071 1500 DEBUG nova.api.openstack.wsgi [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a19c2d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:06:07.080 1500 DEBUG nova.compute.api [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 14, 5, 1, 11, 685682, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:06:07.104 1500 DEBUG oslo_concurrency.lockutils [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:06:07.104 1500 DEBUG oslo_concurrency.lockutils [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:06:07.184 1500 DEBUG nova.compute.api [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:06:07.185 1500 DEBUG nova.compute.api [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:06:07.186 1500 DEBUG oslo_concurrency.lockutils [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:06:07.187 1500 DEBUG oslo_concurrency.lockutils [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:06:07.284 1500 DEBUG nova.policy [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'f875a10b07be43c197ef478066dc3a8e', 'roles': [u'admin', u'ResellerAdmin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'007b5c587a144e49a50c9008f27cd2bd', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:06:07.288 1500 INFO nova.osapi_compute.wsgi.server [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] 10.0.20.22 "GET /v2.1/007b5c587a144e49a50c9008f27cd2bd/servers/detail?all_tenants=True&changes-since=2018-09-14T05%3A01%3A11.685682%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.2364478
2018-09-14 01:06:07.782 1495 DEBUG nova.api.openstack.wsgi [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a19c2d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:06:07.788 1495 DEBUG nova.compute.api [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 14, 5, 1, 23, 799035, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:06:07.814 1495 DEBUG oslo_concurrency.lockutils [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:06:07.815 1495 DEBUG oslo_concurrency.lockutils [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:06:07.894 1495 DEBUG nova.compute.api [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:06:07.895 1495 DEBUG nova.compute.api [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:06:07.897 1495 DEBUG oslo_concurrency.lockutils [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:06:07.897 1495 DEBUG oslo_concurrency.lockutils [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:06:07.981 1495 DEBUG nova.policy [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'f875a10b07be43c197ef478066dc3a8e', 'roles': [u'admin', u'ResellerAdmin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'007b5c587a144e49a50c9008f27cd2bd', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:06:07.985 1495 INFO nova.osapi_compute.wsgi.server [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] 10.0.20.22 "GET /v2.1/007b5c587a144e49a50c9008f27cd2bd/servers/detail?all_tenants=True&changes-since=2018-09-14T05%3A01%3A23.799035%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.2184379
2018-09-14 01:06:19.495 1497 DEBUG nova.osapi_compute.wsgi.server [req-0b6e604e-6bb3-437a-8b5d-8844f272e0ed 4fcbea5093974dfa8d32817aed2734e4 e0b884885d7c405cb472bb251fc6d267 - 5a1239454d7f47efb51dce7c0981420a 5a1239454d7f47efb51dce7c0981420a] (1497) accepted ('10.0.20.22', 57206) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:06:19.982 1497 DEBUG nova.api.openstack.wsgi [req-d8ba46e5-4fa1-42f5-9afa-4303cf8cc4a8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Action: 'create', calling method: <function version_select at 0x7f8e298a47d0>, body: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsVSuutcWyvybgSHZc2N9EXQZ0huG9nx2Joe+A92WcgTUC3HbGOdBQneZyzWgzSN4fYhR/aeD+ByyidInVrF0hH/G16UG8jFx7lLgT7JSasn3IlsyP9I4ulYoj+N/tglecEI2cmJXshUfAsNEfBUGvFzFpsQTBu82pme88hgqgKawOG2a2fjJjHjGLNC8Ne/VfnAbjuuMTQYBB15MONc1cHShZSnBE0J7AoBX8ua1o0HwXro31cJUPfV8mNV9mhnNKDnz4zKgGMzVm+eQW5nUoVdNdtTgGGIgbtuZylA2eF+t7VYhWbHTcOyx37tWqTXaizoDyTgskwWbBx49vfMD9 root@localhost.localdomain\n", "name": "tempest-keypair-1536901521"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-14 01:06:20.028 1497 DEBUG nova.quota [req-d8ba46e5-4fa1-42f5-9afa-4303cf8cc4a8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Getting quotas for project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-14 01:06:20.036 1497 DEBUG nova.quota [req-d8ba46e5-4fa1-42f5-9afa-4303cf8cc4a8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Getting quotas for user 320bb866067645eeb9e80a7fdac1faec and project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-14 01:06:20.102 1497 INFO nova.osapi_compute.wsgi.server [req-d8ba46e5-4fa1-42f5-9afa-4303cf8cc4a8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "POST /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/os-keypairs HTTP/1.1" status: 200 len: 997 time: 0.6026921
2018-09-14 01:06:26.072 1503 DEBUG nova.osapi_compute.wsgi.server [req-1d0a3dd8-c145-4ec0-8fef-83c98876dc84 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] (1503) accepted ('10.0.20.22', 57468) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:06:26.482 1503 DEBUG nova.api.openstack.wsgi [req-b43183e7-37bf-4380-9412-dd5305945e41 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<function version_select at 0x7f8e29a8d6e0>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:06:26.516 1503 DEBUG oslo_db.sqlalchemy.engines [req-b43183e7-37bf-4380-9412-dd5305945e41 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 01:06:26.524 1503 WARNING oslo_db.sqlalchemy.utils [req-b43183e7-37bf-4380-9412-dd5305945e41 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-14 01:06:26.542 1503 WARNING oslo_db.sqlalchemy.utils [req-b43183e7-37bf-4380-9412-dd5305945e41 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-14 01:06:26.560 1503 INFO nova.osapi_compute.wsgi.server [req-b43183e7-37bf-4380-9412-dd5305945e41 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/os-keypairs HTTP/1.1" status: 200 len: 966 time: 0.4842529
2018-09-14 01:08:20.415 1495 DEBUG nova.osapi_compute.wsgi.server [req-0390b630-d553-44d7-bd0b-d61c5ceb8e48 f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] (1495) accepted ('10.0.20.22', 59414) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:08:20.850 1495 DEBUG nova.api.openstack.wsgi [req-0548274c-d472-4072-bea7-c1b354187c38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8e2a4c9dd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:20.929 1495 INFO nova.api.openstack.wsgi [req-0548274c-d472-4072-bea7-c1b354187c38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] HTTP exception thrown: Flavor m1.tiny could not be found.
2018-09-14 01:08:20.930 1495 DEBUG nova.api.openstack.wsgi [req-0548274c-d472-4072-bea7-c1b354187c38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Returning 404 to user: Flavor m1.tiny could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-14 01:08:20.933 1495 INFO nova.osapi_compute.wsgi.server [req-0548274c-d472-4072-bea7-c1b354187c38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/flavors/m1.tiny HTTP/1.1" status: 404 len: 500 time: 0.5145760
2018-09-14 01:08:20.949 1495 DEBUG nova.api.openstack.wsgi [req-743f1646-0b8b-41e8-8e89-7ef8ab366d83 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8e2a4c95d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:21.028 1495 INFO nova.osapi_compute.wsgi.server [req-743f1646-0b8b-41e8-8e89-7ef8ab366d83 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/flavors HTTP/1.1" status: 200 len: 2106 time: 0.0839729
2018-09-14 01:08:21.040 1495 DEBUG nova.api.openstack.wsgi [req-15352930-0e12-4f70-8929-b4d4469844cc 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8e2a4c9dd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:21.062 1495 INFO nova.osapi_compute.wsgi.server [req-15352930-0e12-4f70-8929-b4d4469844cc 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0270150
2018-09-14 01:08:23.849 1495 DEBUG nova.api.openstack.wsgi [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Action: 'create', calling method: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a232090>>, body: {"server": {"name": "tempest-INSTANCE_SAMPLE-1536901521", "imageRef": "6b76ac65-6a92-4eb9-af79-45a9562ec0a6", "key_name": "tempest-keypair-1536901521", "flavorRef": "1", "max_count": 1, "min_count": 1, "networks": [{"uuid": "9b85a1da-969d-4a99-a856-9ea260adb0b7"}], "security_groups": [{"name": "1242d158-6167-4a8c-af70-67c7d7331279"}]}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-14 01:08:23.920 1495 DEBUG oslo_concurrency.lockutils [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:23.922 1495 DEBUG oslo_concurrency.lockutils [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:23.937 1495 DEBUG oslo_concurrency.lockutils [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:23.938 1495 DEBUG oslo_concurrency.lockutils [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:23.981 1495 WARNING nova.image.glance [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 01:08:26.854 1495 DEBUG nova.network.neutronv2.api [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] validate_networks() for [(u'9b85a1da-969d-4a99-a856-9ea260adb0b7', None, None, None)] validate_networks /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1692
2018-09-14 01:08:27.220 1495 DEBUG nova.virt.hardware [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] emulator threads policy constraint: None get_emulator_threads_constraint /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1289
2018-09-14 01:08:27.254 1495 DEBUG nova.quota [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Getting quotas for project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-14 01:08:27.265 1495 DEBUG nova.quota [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Getting quotas for user 320bb866067645eeb9e80a7fdac1faec and project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-14 01:08:27.630 1495 DEBUG nova.quota [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Getting quotas for project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-14 01:08:27.637 1495 DEBUG nova.quota [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Getting quotas for user 320bb866067645eeb9e80a7fdac1faec and project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-14 01:08:27.674 1495 DEBUG nova.quota [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Getting quotas for project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-14 01:08:27.682 1495 DEBUG nova.quota [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Getting quotas for user 320bb866067645eeb9e80a7fdac1faec and project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-14 01:08:27.706 1495 DEBUG nova.context [req-29e52604-a532-4812-90a1-187a3bd6dd1b - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-14 01:08:27.708 1495 DEBUG oslo_concurrency.lockutils [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:27.709 1495 DEBUG oslo_concurrency.lockutils [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:27.710 1495 DEBUG oslo_concurrency.lockutils [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:27.711 1495 DEBUG oslo_concurrency.lockutils [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:27.739 1495 DEBUG nova.quota [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Getting quotas for project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-14 01:08:27.745 1495 DEBUG nova.quota [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Getting quotas for user 320bb866067645eeb9e80a7fdac1faec and project b373e29d0c3a4c9d8c00459e98efe8cb. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-14 01:08:27.758 1495 DEBUG nova.compute.api [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Going to run 1 instances... _provision_instances /usr/lib/python2.7/site-packages/nova/compute/api.py:891
2018-09-14 01:08:27.789 1495 DEBUG nova.compute.api [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='6b76ac65-6a92-4eb9-af79-45a9562ec0a6',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _bdm_validate_set_size_and_instance /usr/lib/python2.7/site-packages/nova/compute/api.py:1268
2018-09-14 01:08:27.895 1495 INFO nova.osapi_compute.wsgi.server [req-e5ca6b2c-b655-4492-9ae3-50bced4bf6d7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "POST /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers HTTP/1.1" status: 202 len: 989 time: 4.0538130
2018-09-14 01:08:27.912 1495 DEBUG nova.api.openstack.wsgi [req-f0db425c-a1cc-48b6-80ed-abe9742c4da7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:27.913 1495 DEBUG nova.compute.api [req-f0db425c-a1cc-48b6-80ed-abe9742c4da7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:08:27.963 1495 DEBUG nova.policy [req-f0db425c-a1cc-48b6-80ed-abe9742c4da7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:08:28.049 1495 INFO nova.osapi_compute.wsgi.server [req-f0db425c-a1cc-48b6-80ed-abe9742c4da7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 1857 time: 0.1447551
2018-09-14 01:08:28.100 1495 DEBUG nova.api.openstack.wsgi [req-8deb6120-931b-475c-82ff-2de31920990e 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8e2a4c9dd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:28.121 1495 INFO nova.osapi_compute.wsgi.server [req-8deb6120-931b-475c-82ff-2de31920990e 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0262861
2018-09-14 01:08:33.010 1500 DEBUG nova.osapi_compute.wsgi.server [req-8ef49283-2789-44cb-a2e5-22495d2eaa6c f875a10b07be43c197ef478066dc3a8e 007b5c587a144e49a50c9008f27cd2bd - default default] (1500) accepted ('10.0.20.22', 59738) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:08:33.516 1500 INFO nova.osapi_compute.wsgi.server [req-cc9b0445-5db6-4782-b19e-595b7112126b 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb HTTP/1.1" status: 404 len: 382 time: 0.5027349
2018-09-14 01:08:33.533 1500 DEBUG nova.api.openstack.wsgi [req-5b7287b2-7d49-4759-be7a-ea54c83e5895 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8e2a539f10>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:33.536 1500 INFO nova.osapi_compute.wsgi.server [req-5b7287b2-7d49-4759-be7a-ea54c83e5895 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0129819
2018-09-14 01:08:33.861 1500 DEBUG nova.api.openstack.wsgi [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:33.865 1500 DEBUG nova.compute.api [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:08:33.888 1500 DEBUG oslo_concurrency.lockutils [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:33.888 1500 DEBUG oslo_concurrency.lockutils [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:33.960 1500 DEBUG nova.compute.api [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:08:33.961 1500 DEBUG nova.compute.api [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:08:33.963 1500 DEBUG oslo_concurrency.lockutils [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:33.964 1500 DEBUG oslo_concurrency.lockutils [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:34.059 1500 INFO nova.osapi_compute.wsgi.server [req-ef9e23c1-b5fd-4b11-80f9-278c7fa9ac21 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 786 time: 0.2069609
2018-09-14 01:08:34.078 1500 DEBUG nova.api.openstack.wsgi [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:34.080 1500 DEBUG nova.compute.api [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:08:34.110 1500 DEBUG oslo_concurrency.lockutils [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:34.111 1500 DEBUG oslo_concurrency.lockutils [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:34.287 1500 DEBUG nova.objects.instance [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lazy-loading 'services' on Instance uuid 9067fe31-e03d-465c-b46b-ceed1141609d obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 01:08:34.396 1500 DEBUG nova.policy [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:08:38.326 1500 INFO nova.osapi_compute.wsgi.server [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 2434 time: 4.2558849
2018-09-14 01:08:42.539 1500 DEBUG nova.osapi_compute.wsgi.server [req-52fae4d3-0598-4b3a-af6b-d32e81be7eb3 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1500) accepted ('10.0.20.22', 60060) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:08:42.981 1500 DEBUG nova.api.openstack.wsgi [req-89713ec3-35b1-48ae-8fdb-cd6e9093c63b 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f8e2a3a4e10>>, body: {"events": [{"tag": "8bb66bed-eca2-444f-82ed-6b32ab344e73", "name": "network-changed", "server_uuid": "9067fe31-e03d-465c-b46b-ceed1141609d"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-14 01:08:42.997 1500 DEBUG oslo_concurrency.lockutils [req-89713ec3-35b1-48ae-8fdb-cd6e9093c63b 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:42.998 1500 DEBUG oslo_concurrency.lockutils [req-89713ec3-35b1-48ae-8fdb-cd6e9093c63b 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:43.028 1500 INFO nova.api.openstack.compute.server_external_events [req-89713ec3-35b1-48ae-8fdb-cd6e9093c63b 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Creating event network-changed:8bb66bed-eca2-444f-82ed-6b32ab344e73 for instance 9067fe31-e03d-465c-b46b-ceed1141609d on localhost.localdomain
2018-09-14 01:08:43.087 1500 INFO nova.osapi_compute.wsgi.server [req-89713ec3-35b1-48ae-8fdb-cd6e9093c63b 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] 10.0.20.22 "POST /v2.1/007b5c587a144e49a50c9008f27cd2bd/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 0.5448349
2018-09-14 01:08:47.369 1500 DEBUG nova.osapi_compute.wsgi.server [req-89713ec3-35b1-48ae-8fdb-cd6e9093c63b 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] (1500) accepted ('10.0.20.22', 60072) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:08:47.886 1500 INFO nova.osapi_compute.wsgi.server [req-0af233e2-e424-487f-aa84-a0295e673d9c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb HTTP/1.1" status: 404 len: 382 time: 0.5142610
2018-09-14 01:08:47.897 1500 DEBUG nova.api.openstack.wsgi [req-b7b62c65-1a0f-46dc-b6bd-3213978fe3e2 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8e2a539f10>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:47.899 1500 INFO nova.osapi_compute.wsgi.server [req-b7b62c65-1a0f-46dc-b6bd-3213978fe3e2 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0082450
2018-09-14 01:08:48.202 1500 DEBUG nova.api.openstack.wsgi [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:48.205 1500 DEBUG nova.compute.api [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:08:48.220 1500 DEBUG oslo_concurrency.lockutils [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:48.224 1500 DEBUG oslo_concurrency.lockutils [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:48.289 1500 DEBUG nova.compute.api [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:08:48.289 1500 DEBUG nova.compute.api [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:08:48.291 1500 DEBUG oslo_concurrency.lockutils [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:48.291 1500 DEBUG oslo_concurrency.lockutils [req-3b37792f-649a-47e7-b578-359d6ea1c026 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:48.339 1500 DEBUG nova.api.openstack.wsgi [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f8e2a3a4e10>>, body: {"events": [{"tag": "8bb66bed-eca2-444f-82ed-6b32ab344e73", "name": "network-vif-deleted", "server_uuid": "9067fe31-e03d-465c-b46b-ceed1141609d"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-14 01:08:48.384 1500 DEBUG oslo_concurrency.lockutils [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:48.385 1500 DEBUG oslo_concurrency.lockutils [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:48.427 1500 DEBUG nova.api.openstack.compute.server_external_events [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Unable to find a host for instance 9067fe31-e03d-465c-b46b-ceed1141609d. Dropping event network-vif-deleted create /usr/lib/python2.7/site-packages/nova/api/openstack/compute/server_external_events.py:138
2018-09-14 01:08:48.428 1500 INFO nova.api.openstack.wsgi [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] HTTP exception thrown: No instances found for any event
2018-09-14 01:08:48.428 1500 DEBUG nova.api.openstack.wsgi [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] Returning 404 to user: No instances found for any event __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-14 01:08:48.431 1500 INFO nova.osapi_compute.wsgi.server [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] 10.0.20.22 "POST /v2.1/007b5c587a144e49a50c9008f27cd2bd/os-server-external-events HTTP/1.1" status: 404 len: 498 time: 0.1006231
2018-09-14 01:08:48.437 1500 INFO nova.osapi_compute.wsgi.server [req-a8f9a8bc-52bf-4cb4-a6e1-afa5358c3a48 26dec8243f6c4398bc7dd6ef297ca5bc 007b5c587a144e49a50c9008f27cd2bd - default default] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 786 time: 0.2407961
2018-09-14 01:08:48.454 1500 DEBUG nova.api.openstack.wsgi [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:48.456 1500 DEBUG nova.compute.api [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:08:48.465 1500 DEBUG oslo_concurrency.lockutils [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:48.466 1500 DEBUG oslo_concurrency.lockutils [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:48.566 1500 DEBUG nova.policy [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:08:49.105 1500 INFO nova.osapi_compute.wsgi.server [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 2267 time: 0.6581640
2018-09-14 01:08:58.956 1500 DEBUG nova.osapi_compute.wsgi.server [req-a4b21a73-02e4-48e1-a811-f493e943045c 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1500) accepted ('10.0.20.22', 60116) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:08:59.457 1500 INFO nova.osapi_compute.wsgi.server [req-de79871a-6ff4-4683-8a2c-f18dbc4fca7b 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb HTTP/1.1" status: 404 len: 382 time: 0.4977801
2018-09-14 01:08:59.468 1500 DEBUG nova.api.openstack.wsgi [req-2a31cd37-b8b0-411f-84b7-e76372a0fa28 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8e2a539f10>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:59.470 1500 INFO nova.osapi_compute.wsgi.server [req-2a31cd37-b8b0-411f-84b7-e76372a0fa28 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0091412
2018-09-14 01:08:59.801 1500 DEBUG nova.api.openstack.wsgi [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:59.805 1500 DEBUG nova.compute.api [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:08:59.820 1500 DEBUG oslo_concurrency.lockutils [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:59.821 1500 DEBUG oslo_concurrency.lockutils [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:59.874 1500 DEBUG nova.compute.api [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:08:59.874 1500 DEBUG nova.compute.api [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:08:59.876 1500 DEBUG oslo_concurrency.lockutils [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:59.876 1500 DEBUG oslo_concurrency.lockutils [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:08:59.944 1500 INFO nova.osapi_compute.wsgi.server [req-90119003-e9db-4f00-9c87-29b22fc36db6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 786 time: 0.1500731
2018-09-14 01:08:59.964 1500 DEBUG nova.api.openstack.wsgi [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:08:59.967 1500 DEBUG nova.compute.api [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:08:59.978 1500 DEBUG oslo_concurrency.lockutils [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:08:59.979 1500 DEBUG oslo_concurrency.lockutils [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:00.083 1500 DEBUG oslo_concurrency.lockutils [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:00.083 1500 DEBUG oslo_concurrency.lockutils [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:00.084 1500 DEBUG nova.objects.instance [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lazy-loading 'fault' on Instance uuid 9067fe31-e03d-465c-b46b-ceed1141609d obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 01:09:00.115 1500 DEBUG nova.policy [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:09:00.587 1500 INFO nova.osapi_compute.wsgi.server [req-9f379725-0721-456e-8e89-6b2489e69ea9 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 3881 time: 0.6327360
2018-09-14 01:09:11.696 1494 DEBUG nova.osapi_compute.wsgi.server [req-6565d39b-da6b-4336-be82-69c54c6a0d15 - - - - -] (1494) accepted ('10.0.20.22', 60668) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:09:11.709 1494 WARNING keystonemiddleware.auth_token [req-6565d39b-da6b-4336-be82-69c54c6a0d15 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-14 01:09:13.253 1494 INFO nova.osapi_compute.wsgi.server [req-6a13b28f-15e3-4926-af50-6b37cc9dd4b8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb HTTP/1.1" status: 404 len: 382 time: 1.5500569
2018-09-14 01:09:13.263 1494 DEBUG nova.api.openstack.wsgi [req-603493c9-4aee-4318-8ade-49d8a7d15a51 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8e2a539f10>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:09:13.265 1494 INFO nova.osapi_compute.wsgi.server [req-603493c9-4aee-4318-8ade-49d8a7d15a51 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0087280
2018-09-14 01:09:13.618 1494 DEBUG nova.api.openstack.wsgi [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:09:13.625 1494 DEBUG nova.compute.api [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:09:13.660 1494 DEBUG oslo_db.sqlalchemy.engines [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 01:09:13.700 1494 DEBUG oslo_concurrency.lockutils [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:13.702 1494 DEBUG oslo_concurrency.lockutils [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:13.724 1494 DEBUG oslo_db.sqlalchemy.engines [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 01:09:13.831 1494 DEBUG nova.compute.api [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-14 01:09:13.832 1494 DEBUG nova.compute.api [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:09:13.833 1494 DEBUG nova.compute.api [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:09:13.834 1494 DEBUG oslo_concurrency.lockutils [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:13.839 1494 DEBUG oslo_concurrency.lockutils [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:13.860 1494 DEBUG oslo_db.sqlalchemy.engines [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 01:09:13.954 1494 INFO nova.osapi_compute.wsgi.server [req-4a97ae64-8fb5-41cd-b32b-2a96bb871b29 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 786 time: 0.3430810
2018-09-14 01:09:13.969 1494 DEBUG nova.api.openstack.wsgi [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:09:13.971 1494 DEBUG nova.compute.api [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:09:13.997 1494 DEBUG oslo_concurrency.lockutils [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:13.998 1494 DEBUG oslo_concurrency.lockutils [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:14.110 1494 DEBUG oslo_concurrency.lockutils [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:14.111 1494 DEBUG oslo_concurrency.lockutils [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:14.112 1494 DEBUG nova.objects.instance [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lazy-loading 'fault' on Instance uuid 9067fe31-e03d-465c-b46b-ceed1141609d obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 01:09:14.155 1494 DEBUG nova.policy [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:09:14.935 1494 INFO nova.osapi_compute.wsgi.server [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 3881 time: 0.9739912
2018-09-14 01:09:28.221 1494 DEBUG nova.osapi_compute.wsgi.server [req-0ce887ee-66be-4e8f-a546-4b5fd300de38 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1494) accepted ('10.0.20.22', 60946) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:09:28.668 1494 INFO nova.osapi_compute.wsgi.server [req-55482294-3fa8-42ad-b3f1-f49c887f4158 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb HTTP/1.1" status: 404 len: 382 time: 0.4448750
2018-09-14 01:09:28.679 1494 DEBUG nova.api.openstack.wsgi [req-a7ca25c1-3b8a-4f1e-bdce-df7b3f812bb7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8e2a539f10>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:09:28.681 1494 INFO nova.osapi_compute.wsgi.server [req-a7ca25c1-3b8a-4f1e-bdce-df7b3f812bb7 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0081170
2018-09-14 01:09:29.013 1494 DEBUG nova.api.openstack.wsgi [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:09:29.016 1494 DEBUG nova.compute.api [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:09:29.029 1494 DEBUG oslo_concurrency.lockutils [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:29.030 1494 DEBUG oslo_concurrency.lockutils [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:29.103 1494 DEBUG nova.compute.api [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:09:29.104 1494 DEBUG nova.compute.api [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:09:29.106 1494 DEBUG oslo_concurrency.lockutils [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:29.107 1494 DEBUG oslo_concurrency.lockutils [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:29.190 1494 INFO nova.osapi_compute.wsgi.server [req-258b982a-4448-4f8c-aacc-0b867051b340 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 786 time: 0.1841850
2018-09-14 01:09:29.209 1494 DEBUG nova.api.openstack.wsgi [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:09:29.210 1494 DEBUG nova.compute.api [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:09:29.225 1494 DEBUG oslo_concurrency.lockutils [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:29.226 1494 DEBUG oslo_concurrency.lockutils [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:29.330 1494 DEBUG oslo_concurrency.lockutils [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:09:29.331 1494 DEBUG oslo_concurrency.lockutils [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:09:29.332 1494 DEBUG nova.objects.instance [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lazy-loading 'fault' on Instance uuid 9067fe31-e03d-465c-b46b-ceed1141609d obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 01:09:29.363 1494 DEBUG nova.policy [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:09:29.846 1494 INFO nova.osapi_compute.wsgi.server [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 3881 time: 0.6462090
2018-09-14 01:10:00.721 1494 DEBUG nova.osapi_compute.wsgi.server [req-93d5117f-0397-41da-9d1d-fd762251db3f 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1494) accepted ('10.0.20.22', 33002) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:10:01.127 1494 DEBUG nova.api.openstack.wsgi [req-f0470161-79d8-4172-ad6e-3636b7853a69 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:01.129 1494 DEBUG nova.compute.api [req-f0470161-79d8-4172-ad6e-3636b7853a69 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1536901521 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-09-14 01:10:01.130 1494 INFO nova.api.openstack.wsgi [req-f0470161-79d8-4172-ad6e-3636b7853a69 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] HTTP exception thrown: Instance tempest-INSTANCE_SAMPLE-1536901521 could not be found.
2018-09-14 01:10:01.131 1494 DEBUG nova.api.openstack.wsgi [req-f0470161-79d8-4172-ad6e-3636b7853a69 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Returning 404 to user: Instance tempest-INSTANCE_SAMPLE-1536901521 could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-14 01:10:01.134 1494 INFO nova.osapi_compute.wsgi.server [req-f0470161-79d8-4172-ad6e-3636b7853a69 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 404 len: 530 time: 0.4105070
2018-09-14 01:10:01.163 1494 DEBUG nova.api.openstack.wsgi [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:01.166 1494 DEBUG nova.compute.api [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:10:01.572 1494 DEBUG oslo_concurrency.lockutils [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:01.573 1494 DEBUG oslo_concurrency.lockutils [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:01.654 1494 DEBUG nova.compute.api [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:10:01.655 1494 DEBUG nova.compute.api [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:10:01.657 1494 DEBUG oslo_concurrency.lockutils [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:01.658 1494 DEBUG oslo_concurrency.lockutils [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:01.740 1494 INFO nova.osapi_compute.wsgi.server [req-97d1f06f-29d7-4cdb-9df3-82ab7f2b0757 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 784 time: 0.5867991
2018-09-14 01:10:01.759 1494 DEBUG nova.api.openstack.wsgi [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:01.762 1494 DEBUG nova.compute.api [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:10:01.775 1494 DEBUG oslo_concurrency.lockutils [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:01.776 1494 DEBUG oslo_concurrency.lockutils [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:01.891 1494 DEBUG oslo_concurrency.lockutils [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:01.892 1494 DEBUG oslo_concurrency.lockutils [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:01.892 1494 DEBUG nova.objects.instance [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lazy-loading 'fault' on Instance uuid 9067fe31-e03d-465c-b46b-ceed1141609d obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 01:10:01.914 1494 DEBUG nova.policy [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:10:02.638 1494 INFO nova.osapi_compute.wsgi.server [req-74453ae4-8e11-47c4-86cb-309860447aee 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 3490 time: 0.8865469
2018-09-14 01:10:02.664 1494 DEBUG nova.api.openstack.wsgi [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Action: 'action', calling method: <function version_select at 0x7f8e2a0c35f0>, body: {"addFloatingIp": {"address": "172.24.4.12"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-14 01:10:02.671 1494 DEBUG nova.compute.api [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:10:02.689 1494 DEBUG oslo_concurrency.lockutils [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:02.692 1494 DEBUG oslo_concurrency.lockutils [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:02.803 1494 WARNING nova.api.openstack.compute.floating_ips [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Info cache is InstanceInfoCache(created_at=2018-09-14T05:08:31Z,deleted=False,deleted_at=None,instance_uuid=9067fe31-e03d-465c-b46b-ceed1141609d,network_info=NetworkModel(),updated_at=2018-09-14T05:08:48Z) during associate with no nw_info cache
2018-09-14 01:10:02.806 1494 INFO nova.api.openstack.wsgi [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] HTTP exception thrown: Instance network is not ready yet
2018-09-14 01:10:02.807 1494 DEBUG nova.api.openstack.wsgi [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Returning 400 to user: Instance network is not ready yet __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-14 01:10:02.813 1494 INFO nova.osapi_compute.wsgi.server [req-3ab728f5-6140-4bfe-a618-8c6adffedd14 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "POST /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d/action HTTP/1.1" status: 400 len: 499 time: 0.1645610
2018-09-14 01:10:11.732 1496 DEBUG nova.osapi_compute.wsgi.server [req-24ff2b62-2081-43e8-96aa-0ecc673273e0 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] (1496) accepted ('10.0.20.22', 33524) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:10:12.227 1496 INFO nova.osapi_compute.wsgi.server [req-48b0776e-00a1-42da-b9d9-605b1d34ed66 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb HTTP/1.1" status: 404 len: 382 time: 0.4898710
2018-09-14 01:10:12.237 1496 DEBUG nova.api.openstack.wsgi [req-d0f77c62-5b16-4f63-80e3-f5fb377515e6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8e2a539f10>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:12.240 1496 INFO nova.osapi_compute.wsgi.server [req-d0f77c62-5b16-4f63-80e3-f5fb377515e6 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0079401
2018-09-14 01:10:12.511 1496 DEBUG nova.api.openstack.wsgi [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a19c2d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:12.516 1496 DEBUG nova.compute.api [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:10:12.545 1496 DEBUG oslo_concurrency.lockutils [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:12.547 1496 DEBUG oslo_concurrency.lockutils [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:12.639 1496 DEBUG nova.compute.api [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:10:12.641 1496 DEBUG nova.compute.api [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:10:12.642 1496 DEBUG oslo_concurrency.lockutils [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:12.643 1496 DEBUG oslo_concurrency.lockutils [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:13.107 1496 DEBUG oslo_concurrency.lockutils [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:13.108 1496 DEBUG oslo_concurrency.lockutils [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:13.124 1496 DEBUG nova.policy [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:10:14.073 1496 INFO nova.osapi_compute.wsgi.server [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/detail HTTP/1.1" status: 200 len: 3884 time: 1.5731390
2018-09-14 01:10:30.431 1496 DEBUG nova.osapi_compute.wsgi.server [req-11c0b09c-14ba-4148-9b72-457df3c2cea8 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1496) accepted ('10.0.20.22', 33846) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:10:30.848 1496 DEBUG nova.api.openstack.wsgi [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a19c2d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:30.851 1496 DEBUG nova.compute.api [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:10:30.867 1496 DEBUG oslo_concurrency.lockutils [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:30.873 1496 DEBUG oslo_concurrency.lockutils [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:30.948 1496 DEBUG nova.compute.api [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:10:30.949 1496 DEBUG nova.compute.api [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:10:30.950 1496 DEBUG oslo_concurrency.lockutils [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:30.950 1496 DEBUG oslo_concurrency.lockutils [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:31.058 1496 DEBUG oslo_concurrency.lockutils [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:31.059 1496 DEBUG oslo_concurrency.lockutils [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:31.072 1496 DEBUG nova.policy [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:10:31.615 1496 INFO nova.osapi_compute.wsgi.server [req-6b5f4f14-a6ba-43c0-913b-5e6645e2cac5 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/detail HTTP/1.1" status: 200 len: 3493 time: 1.1819558
2018-09-14 01:10:39.862 1503 DEBUG nova.osapi_compute.wsgi.server [req-b43183e7-37bf-4380-9412-dd5305945e41 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1503) accepted ('10.0.20.22', 34114) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:10:40.236 1503 DEBUG nova.api.openstack.wsgi [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a19c2d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:40.240 1503 DEBUG nova.compute.api [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:10:40.273 1503 DEBUG oslo_concurrency.lockutils [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:40.275 1503 DEBUG oslo_concurrency.lockutils [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:40.296 1503 DEBUG oslo_db.sqlalchemy.engines [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 01:10:40.405 1503 DEBUG nova.compute.api [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-14 01:10:40.406 1503 DEBUG nova.compute.api [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:10:40.406 1503 DEBUG nova.compute.api [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:10:40.407 1503 DEBUG oslo_concurrency.lockutils [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:40.412 1503 DEBUG oslo_concurrency.lockutils [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:40.432 1503 DEBUG oslo_db.sqlalchemy.engines [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 01:10:40.583 1503 DEBUG oslo_concurrency.lockutils [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:40.584 1503 DEBUG oslo_concurrency.lockutils [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:40.600 1503 DEBUG nova.policy [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:10:41.459 1503 INFO nova.osapi_compute.wsgi.server [req-f3932d74-102e-4832-9bd3-919efcae4697 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/detail HTTP/1.1" status: 200 len: 3493 time: 1.5934010
2018-09-14 01:10:53.951 1495 DEBUG nova.osapi_compute.wsgi.server [req-8deb6120-931b-475c-82ff-2de31920990e 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1495) accepted ('10.0.20.22', 34136) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:10:54.318 1495 DEBUG nova.api.openstack.wsgi [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a19c2d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:10:54.321 1495 DEBUG nova.compute.api [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:10:54.340 1495 DEBUG oslo_concurrency.lockutils [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:54.341 1495 DEBUG oslo_concurrency.lockutils [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:54.399 1495 DEBUG nova.compute.api [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:10:54.399 1495 DEBUG nova.compute.api [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:10:54.400 1495 DEBUG oslo_concurrency.lockutils [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:54.401 1495 DEBUG oslo_concurrency.lockutils [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:54.495 1495 DEBUG oslo_concurrency.lockutils [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:10:54.495 1495 DEBUG oslo_concurrency.lockutils [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:10:54.510 1495 DEBUG nova.policy [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:10:54.970 1495 INFO nova.osapi_compute.wsgi.server [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/detail HTTP/1.1" status: 200 len: 3493 time: 1.0168061
2018-09-14 01:11:02.034 1495 DEBUG nova.osapi_compute.wsgi.server [req-c78cfe28-8f27-4be3-8c97-9bd8a9c28b10 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] (1495) accepted ('10.0.20.22', 34144) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-14 01:11:02.701 1495 DEBUG nova.api.openstack.wsgi [req-1f3c0b22-ae8f-44a3-8629-4fb77095cb71 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:11:02.702 1495 DEBUG nova.compute.api [req-1f3c0b22-ae8f-44a3-8629-4fb77095cb71 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1536901521 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-09-14 01:11:02.703 1495 INFO nova.api.openstack.wsgi [req-1f3c0b22-ae8f-44a3-8629-4fb77095cb71 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] HTTP exception thrown: Instance tempest-INSTANCE_SAMPLE-1536901521 could not be found.
2018-09-14 01:11:02.704 1495 DEBUG nova.api.openstack.wsgi [req-1f3c0b22-ae8f-44a3-8629-4fb77095cb71 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Returning 404 to user: Instance tempest-INSTANCE_SAMPLE-1536901521 could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-14 01:11:02.706 1495 INFO nova.osapi_compute.wsgi.server [req-1f3c0b22-ae8f-44a3-8629-4fb77095cb71 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 404 len: 530 time: 0.6679411
2018-09-14 01:11:02.729 1495 DEBUG nova.api.openstack.wsgi [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a1e81d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:11:02.732 1495 DEBUG nova.compute.api [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Searching by: {'deleted': False, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', u'name': u'tempest-INSTANCE_SAMPLE-1536901521'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-14 01:11:02.764 1495 DEBUG oslo_concurrency.lockutils [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:11:02.765 1495 DEBUG oslo_concurrency.lockutils [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:11:02.869 1495 DEBUG nova.compute.api [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-14 01:11:02.870 1495 DEBUG nova.compute.api [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Listing 1000 instances in cell 67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-14 01:11:02.872 1495 DEBUG oslo_concurrency.lockutils [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:11:02.873 1495 DEBUG oslo_concurrency.lockutils [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:11:02.955 1495 INFO nova.osapi_compute.wsgi.server [req-082d5cea-3147-46a5-86b8-36a7fbd92a34 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers?name=tempest-INSTANCE_SAMPLE-1536901521 HTTP/1.1" status: 200 len: 784 time: 0.2377191
2018-09-14 01:11:02.978 1495 DEBUG nova.api.openstack.wsgi [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8e2a0bd650>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-14 01:11:02.980 1495 DEBUG nova.compute.api [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:11:03.002 1495 DEBUG oslo_concurrency.lockutils [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:11:03.004 1495 DEBUG oslo_concurrency.lockutils [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:11:03.139 1495 DEBUG oslo_concurrency.lockutils [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:11:03.140 1495 DEBUG oslo_concurrency.lockutils [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:11:03.141 1495 DEBUG nova.objects.instance [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lazy-loading 'fault' on Instance uuid 9067fe31-e03d-465c-b46b-ceed1141609d obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 01:11:03.182 1495 DEBUG nova.policy [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'320bb866067645eeb9e80a7fdac1faec', 'roles': [u'admin'], 'user_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b373e29d0c3a4c9d8c00459e98efe8cb', 'project_domain_id': u'a34d39cd8f4d4d9e90c4a901d272c9f0'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-14 01:11:03.965 1495 INFO nova.osapi_compute.wsgi.server [req-02b14aae-02d4-4aa9-8233-cca66459ebbe 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "GET /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d HTTP/1.1" status: 200 len: 3490 time: 0.9940970
2018-09-14 01:11:06.833 1495 DEBUG nova.api.openstack.wsgi [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Action: 'create', calling method: <bound method VolumeAttachmentController.create of <nova.api.openstack.compute.volumes.VolumeAttachmentController object at 0x7f8e29fcae10>>, body: {"volumeAttachment": {"device": "/dev/vdb", "volumeId": "80cea6c1-03bd-41d2-896d-72d7c28055d2"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-14 01:11:06.837 1495 DEBUG nova.compute.api [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] [instance: 9067fe31-e03d-465c-b46b-ceed1141609d] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-14 01:11:06.849 1495 DEBUG oslo_concurrency.lockutils [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 01:11:06.850 1495 DEBUG oslo_concurrency.lockutils [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 01:11:06.933 1495 INFO nova.api.openstack.wsgi [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] HTTP exception thrown: Cannot 'attach_volume' instance 9067fe31-e03d-465c-b46b-ceed1141609d while it is in vm_state error
2018-09-14 01:11:06.934 1495 DEBUG nova.api.openstack.wsgi [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] Returning 409 to user: Cannot 'attach_volume' instance 9067fe31-e03d-465c-b46b-ceed1141609d while it is in vm_state error __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-14 01:11:06.935 1495 INFO nova.osapi_compute.wsgi.server [req-56ddd8ed-02dd-41bc-a6e4-ffdf38400898 320bb866067645eeb9e80a7fdac1faec b373e29d0c3a4c9d8c00459e98efe8cb - a34d39cd8f4d4d9e90c4a901d272c9f0 a34d39cd8f4d4d9e90c4a901d272c9f0] 10.0.20.22 "POST /v2.1/b373e29d0c3a4c9d8c00459e98efe8cb/servers/9067fe31-e03d-465c-b46b-ceed1141609d/os-volume_attachments HTTP/1.1" status: 409 len: 570 time: 0.1125939
