2018-09-28 13:41:04.409 4035 DEBUG oslo_db.sqlalchemy.engines [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 13:41:08.430 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 13:41:08.435 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 13:41:08.460 4035 DEBUG oslo_db.sqlalchemy.engines [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 13:41:08.674 4035 DEBUG nova.context [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),d6ebb650-317a-44ff-9b75-bd1a36697143(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-28 13:41:08.675 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 13:41:08.676 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 13:41:08.677 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 13:41:08.677 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 13:41:08.701 4035 DEBUG oslo_db.sqlalchemy.engines [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 13:41:08.731 4035 DEBUG nova.quota [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Getting quotas for project 314b158449144a339a00614d0cddbdda. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 13:41:08.738 4035 DEBUG nova.quota [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Getting quotas for user 4d7b8e283af74612931c4fc2af657a01 and project 314b158449144a339a00614d0cddbdda. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 13:41:08.764 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 13:41:08.765 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 13:41:08.765 4035 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:08.838 4035 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 13:41:08.841 4035 DEBUG nova.objects.instance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lazy-loading 'tags' on Instance uuid b6131194-0918-4d84-88e9-9495bd76a5eb obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-28 13:41:08.896 4035 DEBUG nova.conductor.manager [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] [instance: b6131194-0918-4d84-88e9-9495bd76a5eb] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='44c43b8c-7ac1-4084-8b92-98c72a8427b0',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _create_block_device_mapping /usr/lib/python2.7/site-packages/nova/conductor/manager.py:968
2018-09-28 13:41:08.899 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 13:41:08.900 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 13:41:09.006 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 13:41:09.007 4035 DEBUG oslo_concurrency.lockutils [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Lock "d6ebb650-317a-44ff-9b75-bd1a36697143" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 13:41:09.402 4036 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:09.476 4036 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 13:41:09.921 4038 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:10.007 4038 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 13:41:10.986 4039 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:11.056 4039 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 13:41:11.416 4041 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:11.488 4041 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 13:41:11.766 4036 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:11.786 4036 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 13:41:25.978 4035 WARNING nova.image.glance [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] No protocol specified in for api_server 'http://10.0.20.23:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 13:41:25.999 4035 DEBUG nova.notifications.objects.base [req-6f3876c4-e1a2-40d4-9128-04f42d8b48fc 4d7b8e283af74612931c4fc2af657a01 314b158449144a339a00614d0cddbdda - 5ab08487c7e34115ac3095299b100867 5ab08487c7e34115ac3095299b100867] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
